MM-28226: Admin Advisor: add mitigation for metric warning job
mattermost/mattermost-server pull request #15379
Opened 2020-09-01 21:30 UTC by catalintomai

#### Summary
Add various mitigations for Admin Advisor metric warning jobs.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28226

2020-09-02 16:59 UTC, fmunshi commented on app/server.go
> +			//banner and bot metrics - send websocket event
nit space at start of comment 
```suggestion
			// Banner and bot metrics - send websocket event
```

2020-09-02 16:59 UTC, fmunshi commented on app/server.go
> +			//bot and banner metrics, do not send the bot message again
```suggestion
			// Bot and banner metrics, do not send the bot message again
```

2020-09-02 17:28 UTC, srkgupta commented on i18n/en.json
>      "translation": "Integrate AD/LDAP"
The Header of the bot message should also be updated as per the screenshot attached in the ticket https://mattermost.atlassian.net/browse/MM-28226.

2020-09-02 17:28 UTC, srkgupta commented on i18n/en.json
>      "translation": "Integrate SAML 2.0"
The Header of the bot message should also be updated as per the screenshot attached in the ticket https://mattermost.atlassian.net/browse/MM-28226.

2020-09-02 17:46 UTC, catalintomai commented
> doCheckNumberOfActiveUsersWarnMetricStatus

Agree, I couldn't find a good place for job business logic tests though - server_test does not cover that. Will look into it one more time.

2020-09-02 17:47 UTC, srkgupta requested changes
Hi @catalintomai 

I am seeing the following issues:

1. Header is not changed for 200-user and 400-user advisory. As per the JIRA ticket, it is expected to change the header for these advisory messages as well. 

2. Banner does not reappear when the nag interval has passed. As per the expectations mentioned in the JIRA ticket, 

`Make banner not reappear upon page refresh (it should only reappear when another advisory is triggered or when the nag interval has passed)`

Infact, for me even when I removed the warn_metric_number_of_active_users_500 entry from systems table, the banner never showed up again. 

I am blocked with further testing on the banner because it does not shows up for any users in the system if its closed once.

2020-09-02 17:54 UTC, catalintomai commented
> Hi @catalintomai
> 
> I am seeing the following issues:
> 
> 1. Header is not changed for 200-user and 400-user advisory. As per the JIRA ticket, it is expected to change the header for these advisory messages as well.
> 2. Banner does not reappear when the nag interval has passed. As per the expectations mentioned in the JIRA ticket,
> 
> `Make banner not reappear upon page refresh (it should only reappear when another advisory is triggered or when the nag interval has passed)`
> 
> Infact, for me even when I removed the warn_metric_number_of_active_users_500 entry from systems table, the banner never showed up again.
> 
> I am blocked with further testing on the banner because it does not shows up for any users in the system if its closed once.

@srkgupta 
#1  - this seems to be an addition to the current design - I'll add the title
#2 - to my understanding the banner should reappear when the nag interval is hit again - but not on refresh anymore(e.g. I set the nag interval to every 2 minutes and for me the banner reappears every 2 minutes if I set the number of active users > 500).

2020-09-02 17:58 UTC, srkgupta commented
@catalintomai can you dismiss the banner and then check if it appears again. I was not able to get the banner be displayed again once it was dismissed once.

2020-09-02 22:21 UTC, catalintomai commented
> @catalintomai can you dismiss the banner and then check if it appears again. I was not able to get the banner be displayed again once it was dismissed once.

@srkgupta I've sent you a video (longer than a minute) -  I can't seem to see the behavior you describe.

> @catalintomai can you dismiss the banner and then check if it appears again. I was not able to get the banner be displayed again once it was dismissed once.

@srkgupta - sent you a DM with a video - it shows the banner re-appearing after the interval expires.

2020-09-03 08:26 UTC, srkgupta commented
Hi @catalintomai 
I did a fresh DB install and it started working fine and I was able to proceed further and test the remaining tests with the banner. I am now seeing the following issue.  Can you please fix the same:

1. When the user clicks on Acknowledge button, the banner now displays the message "Thank you for contacting Mattermost. We will follow up with you soon." However there is no X button when this message is shown. As a result, the user will not be able to dismiss this message ever again until the user reloads the page. Can you please add a Dismiss button to this message 
![Screenshot 2020-09-03 at 1 47 39 PM](https://user-images.githubusercontent.com/1429138/92089646-10508a80-edec-11ea-8de0-2e38543ddc3f.png)

2020-09-03 13:56 UTC, catalintomai commented
@srkgupta - I asked exactly this question of @esadur yesterday =). Eric - should we add the X button back for the ack banner?

2020-09-03 23:16 UTC, esadur commented
> @srkgupta - I asked exactly this question of @esadur yesterday =). Eric - should we add the X button back for the ack banner?

@catalintomai yes, we should add the X button for the success banner.

2020-09-07 09:28 UTC, srkgupta approved these changes
Tested the updated PR and all the issues are fixed now and the PR is working fine as expected. Approving the PR.

2020-09-07 09:29 UTC, srkgupta commented
/update-branch

2020-09-08 14:51 UTC, merged

2020-09-08 14:51 UTC, mattermod commented
@catalintomai
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Fetching origin
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-server-#15379-upstream-release-5.27-1599576679
Branch 'automated-cherry-pick-of-mattermost-server-#15379-upstream-release-5.27-1599576679' set up to track remote branch 'release-5.27' from 'upstream'.

+++ About to attempt cherry pick of PR #15379 with merge commit f0eb67fa0d0fe95769e73a69e0735b5372e75e52.


+++ Conflicts detected:

UU app/server.go

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2020-09-08 15:18 UTC, catalintomai commented
@amyblais - manually cherry-picked into 5.27