[MM-27952] Fix some logging related races
mattermost/mattermost-server pull request #15404
Opened 2020-09-07 16:16 UTC by streamer45

#### Summary

PR fixes a couple of races related to logging. There are [more](https://mattermost.atlassian.net/browse/MM-28399) but at least this should enable us to run tests with `-count > 1`.

#### Tickets

https://mattermost.atlassian.net/browse/MM-27951
https://mattermost.atlassian.net/browse/MM-27952

2020-09-07 17:12 UTC, wiggin77 approved these changes
LGTM - whoops one problem...

2020-09-07 17:20 UTC, wiggin77 requested changes
initLogging must be after configStore set up.

2020-09-08 02:57 UTC, agnivade approved these changes

2020-09-08 14:42 UTC, wiggin77 approved these changes
:+1:

2020-09-08 14:45 UTC, streamer45 commented
@lindalumitchell 

this only affects tests so there shouldn't be much need for QA.

2020-09-08 18:32 UTC, lindalumitchell approved these changes

2020-09-08 18:36 UTC, merged