[MM-28124] api4/post: return error at getFlaggedPostsForUser
mattermost/mattermost-server pull request #15493
Opened 2020-09-14 16:57 UTC by isacikgoz

#### Summary
If we get an error from the methods `(*App).GetFlaggedPosts` we need to stop execution and return so that we don't get nil pointer dereference. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28124

2020-09-14 17:47 UTC, agnivade requested changes
Would it also be possible to add a test for this? :)

2020-09-15 03:19 UTC, agnivade commented
Hmm .. the test is gone now :thinking:

2020-09-15 07:25 UTC, agnivade approved these changes
Nothing blocking.

2020-09-15 07:25 UTC, agnivade commented on api4/post_test.go
> +	mockPostStore.On("GetFlaggedPosts", mock.Anything, mock.Anything, mock.Anything).Return(nil, errors.New("some-error"))
Nit: The params are builtin types - string, int, int. We could use `mock.AnythingOfType("string"), mock.AnythingOfType("int"), mock.AnythingOfType("int")`

2020-09-15 07:25 UTC, agnivade commented on api4/post_test.go
> +	mockPostStore.On("ClearCaches", mock.Anything).Return()
`ClearCaches` doesn't take any params. Is there a reason we need to use mock.Anything?

2020-09-25 15:10 UTC, mgdelacroix approved these changes
LGTM! :+1:

2020-09-25 15:10 UTC, mgdelacroix commented on api4/post_test.go
> +	th.App.Srv().Store = &mockStore
nit: can we restore the `Store` value after this test case just in case someone decides to add another one after?

2020-09-28 09:40 UTC, isacikgoz commented
/update-branch

2020-09-28 09:41 UTC, isacikgoz commented
@lindalumitchell This is a fix where an error handling code is written in wrong order. Automated tests should be sufficient for this one.

2020-09-29 01:42 UTC, lindalumitchell approved these changes

2020-09-29 07:33 UTC, merged