Add build number to docker tag for cloud-beta releases
mattermost/mattermost-server pull request #15609
Opened 2020-09-25 16:01 UTC by jwilander

#### Summary
Add build number to docker tag for cloud-beta releases. This is needed because if the webapp changes but the server doesn't, the new build will use the same server hash and it will update the existing docker tag which could be deployed somewhere. This should make every build make a unique docker tag.

2020-09-25 16:14 UTC, metanerd approved these changes
LGTM

2020-09-28 07:30 UTC, cpanato requested changes

2020-09-28 07:30 UTC, cpanato commented on build/Jenkinsfile.branch
> +            export TAG=\$(git rev-parse --short=7 HEAD)-\${BUILD_NUMBER}
it is  `${env.BUILD_NUMBER}` , see the other usages of this env var in the code

2020-09-28 16:50 UTC, jwilander commented
Going to merge since it's a small change

2020-09-28 16:50 UTC, merged

2020-09-29 07:51 UTC, cpanato reviewed
late lgtm