Added GoDoc for functions mentioned in Task 7 (#14004) team_store.go
mattermost/mattermost-server pull request #15762
Opened 2020-10-04 08:35 UTC by palcodes

#### Summary

This PR adds GoDoc for the functions mentioned in #14004 

* Fixes -> https://github.com/mattermost/mattermost-server/issues/14004
* JIRA ticket -> https://mattermost.atlassian.net/browse/MM-23002

2020-10-04 08:35 UTC, mattermod commented
Hello @palcodes,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-04 11:00 UTC, jespino commented on store/sqlstore/team_store.go
> +// GetMembers returns a list of members from the database that match the teamId passed as parameter
I would expect some extra information here around the `teamMemberGetOoptions` parameter, something like "the teamMembersGetOptions parameter allow you to restrict what is visible to the user, sort the results or exclude deleted users".

2020-10-04 11:02 UTC, jespino commented on store/sqlstore/team_store.go
> +// GetTotalMemberCount returns the number of all members in a team for the teamId passed as a parameter.
I would expect here to see something about the `restrictions` parameter. Something like "The restrictions parameters allows you to define the set of channels and teams that are visible to the caller of the query, and applies that restrictions to the results."

I would expect something similar in the other places where `restrictions` is passed as parameter.

2020-10-04 11:03 UTC, jespino requested changes
It is looking great, but i would love to have a bit more info about the most complex parameters passed in the functions. Thanks @palcodes!

2020-10-04 11:43 UTC, palcodes commented
@jespino yea, that makes sense. I will get to it.

2020-10-05 07:51 UTC, jespino approved these changes
Now looks good to me. Thanks @palcodes! :confetti_ball:

2020-10-05 09:43 UTC, palcodes commented
Hey, thanks for approving. Meet u on my next contribution 🤗

2020-10-07 08:57 UTC, hanzei commented
/update-branch

2020-10-07 19:42 UTC, justinegeffen commented on store/sqlstore/team_store.go
> +// GetMember returns a single member of the team that matches the teamId and userId provided as parameters
```suggestion
// GetMember returns a single member of the team that matches the teamId and userId provided as parameters.
```

2020-10-07 19:43 UTC, justinegeffen commented on store/sqlstore/team_store.go
> +// GetMembersByIds returns a list of members from the database that matches the teamId and the list of userIds passed as parameters
```suggestion
// GetMembersByIds returns a list of members from the database that matches the teamId and the list of userIds passed as parameters.
```

2020-10-07 19:43 UTC, justinegeffen approved these changes

2020-10-07 19:44 UTC, justinegeffen commented
Just one comment from me, otherwise looks awesome. Thank you!

2020-10-08 12:00 UTC, palcodes commented
I have made the required punctuation changes, what's the current status of the PR?

2020-10-08 20:08 UTC, hanzei commented
/update-branch

2020-10-08 21:13 UTC, hanzei commented
The PR is good to go, but the pipeline fails for unknown reasons. Let me look into it.

2020-10-12 08:36 UTC, hanzei commented
/update-branch

2020-10-13 07:50 UTC, hanzei commented
/update-branch

2020-10-13 20:42 UTC, jespino commented
/update-branch

2020-10-14 10:22 UTC, hanzei commented
/update-branch

2020-10-14 10:53 UTC, merged

2020-10-14 10:54 UTC, hanzei commented
Finally CI is green. Sorry it took so long. Thanks for the PR @palcodes :+1: