Remove direct Store calls from the Api layer for the file api4/system…
mattermost/mattermost-server pull request #15794
Opened 2020-10-05 20:57 UTC by sheetalsingala

…_local.go

#### Summary

#### Ticket Link

2020-10-05 21:03 UTC, mattermod commented
Hello @sheetalsingala,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-05 21:05 UTC, sheetalsingala commented
/check-cla

2020-10-05 22:39 UTC, jasonblais commented
Thank you @sheetalsingala for the contribution! Are you open to help review the failed tests noted above? If you need any help, let us know! Happy to help :)

2020-10-06 07:20 UTC, reflog requested changes

2020-10-06 07:20 UTC, reflog commented on app/app.go
> +func (a *App) CheckIntegrity() <-chan model.IntegrityCheckResult {
Hi. Thanks for the contribution.

This change seems incorrect. you are just returning an empty channel.
instead, it should forward the work to the Store method.

Also, please run `gofmt -s -w` on the source code before committing to conform to code style.

2020-10-13 07:48 UTC, hanzei commented
@sheetalsingala Could you please resolve the merge conflict and then run ` make app-layers`?

2020-10-19 08:39 UTC, jespino commented on app/app.go
> +	return a.Srv().Store.CheckIntegrity
Here you are returning the `CheckIntegrity` function instead of the result of executing the `CheckIntegrity` function.

2020-10-19 08:39 UTC, jespino commented on app/app.go
> +func (a *App) DBHealthCheckWrite() error {
Why this new functions are needed? I don't see any changes in the code calling this new functions.

2020-10-19 09:15 UTC, jespino requested changes
Some changes needed, but almost there.

2020-10-30 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-30 04:27 UTC, jasonblais commented
@sheetalsingala thank you for your contribution! Let us know if you have any questions about the feedback above? Happy to help!

2021-02-16 04:37 UTC, agnivade commented
Hi @sheetalsingala - how is it going with this? Please let us know if we can help in any way. Thanks!

2021-03-26 23:15 UTC, jasonblais commented
@sheetalsingala Big thanks for your contribution!

However, it has been a few months with no activity, so this contribution is considered orphaned and closed.

If there are any areas we can help clarify or provide guidance, let us know! We'd be happy to help :)

2021-03-26 23:15 UTC, closed without merging