MM-20684 old changes along with new tests added
mattermost/mattermost-server pull request #15923
Opened 2020-10-12 17:33 UTC by KrishnaSindhur

#### Summary

#### Ticket Link

2020-10-12 17:33 UTC, mattermod commented
Hello @KrishnaSindhur,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-13 07:51 UTC, hanzei commented
@KrishnaSindhur Does this PR replace https://github.com/mattermost/mattermost-server/pull/14810?

2020-10-13 09:52 UTC, KrishnaSindhur commented
> #14810

yes

2020-10-13 09:54 UTC, KrishnaSindhur commented
> @KrishnaSindhur Does this PR replace #14810?

yes it is

2020-10-19 13:22 UTC, levb approved these changes

2020-10-19 13:22 UTC, levb commented
/update-branch

2020-10-30 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-30 04:28 UTC, jasonblais commented
@iomodo kind reminder to help with reviews :)

2020-11-21 10:50 UTC, iomodo requested changes
Looks good @KrishnaSindhur!
Couple of comments below

2020-11-21 10:50 UTC, iomodo commented on app/command_autocomplete.go
> +	if len(arg.Name) == 0 && arg.Type == model.AutocompleteArgTypeBool {
`parseNamedArgument` will not be called if `arg.Name` is empty. What is the point this check?

2020-11-21 10:50 UTC, iomodo commented on app/command_autocomplete.go
> +			return true, parsed + toBeParsed, "", model.AutocompleteSuggestion{Complete: parsed + toBeParsed + namedArg + " " + "true" + " ", Suggestion: "true", Hint: "", Description: arg.HelpText}
Do we need to suggest "true" here? Isn't just an argument name enough?
Example: `/command --randomize` will mean `randomize` argument is set(to true), and `/command` will mean `randomize` argument is not set(therefore is false).

2020-11-21 10:50 UTC, iomodo commented on app/command_autocomplete.go
> +			return true, parsed + toBeParsed, "", model.AutocompleteSuggestion{Complete: parsed + toBeParsed + namedArg[len(in):] + " " + "true" + " ", Suggestion: "true", Hint: "", Description: arg.HelpText}
same here, when bool type argument is named we do not need `true` and `false`, just `--argname` is enough

2020-11-21 10:50 UTC, iomodo commented on app/command_autocomplete.go
> +		return true, parsed + toBeParsed, "", model.AutocompleteSuggestion{Complete: parsed + toBeParsed, Suggestion: "", Hint: a.Hint, Description: arg.HelpText}
Shouldn't we have two suggestions here? `true` and `false`?

2021-03-12 09:41 UTC, isacikgoz commented
Hey @KrishnaSindhur Are you still planning to work on this issue? Please let us know if there is something we can help with.

2021-03-13 07:42 UTC, KrishnaSindhur commented
> Hey @KrishnaSindhur Are you still planning to work on this issue? Please let us know if there is something we can help with.

I am occupied with some other work, it will take some time to look into it

2021-09-07 06:44 UTC, isacikgoz commented
Hey @KrishnaSindhur did you find some time to work on this ticket? Please let us know if you need some help.

2023-04-25 12:06 UTC, isacikgoz commented
Hi @KrishnaSindhur, big thanks for your contribution! There hasn't been recent activity on this PR so I've marked it as inactive. Following our [inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), the PR is now closed due to 30 days or more of inactivity.

However, if you're still interested working on the changes, let us know! Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420), which may require you to resubmit the changes. 

If you have any questions, don't hesitate to let us know, we're happy to help.

2023-04-25 12:06 UTC, closed without merging