[MM-25408] Improve the grammar on Account Creation Screen
mattermost/mattermost-server pull request #15978
Opened 2020-10-15 21:59 UTC by y-martinez

#### Summary

This PR changes the error message that appears in the Account Creation Screen if the email address you entered does not belong to the accepted domain. This is the result after the change (see screenshot)

![mattermost](https://user-images.githubusercontent.com/6761059/96190231-e2448700-0f0f-11eb-9fde-1754b3784a32.png)

#### Ticket Link

Fix: #15927 
JIRA: https://mattermost.atlassian.net/browse/MM-25408

2020-10-15 21:59 UTC, mattermod commented
Hello @y-martinez,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-15 22:02 UTC, y-martinez commented
/release-note-none

2020-10-15 22:06 UTC, y-martinez commented
/check-cla

2020-10-15 22:24 UTC, y-martinez commented
/release-note-none

2020-10-16 11:11 UTC, ashishbhate commented
A few things to check:

1. That error is used in other places too. It might not be correct to change the error message in those places, especially if those errors return multiple emails (where the plural form may be correct). 

2. The webapp has end to end (e2e) cypress tests that will need to be updated as well:

- https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js#L324

- https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/invite_user_to_closed_team_spec.js#L40

- https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js#L68

2020-10-16 14:50 UTC, y-martinez commented
> A few things to check:
> 
> 1. That error is used in other places too. It might not be correct to change the error message in those places, especially if those errors return multiple emails (where the plural form may be correct).
> 2. The webapp has end to end (e2e) cypress tests that will need to be updated as well:
> 
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js#L324
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/invite_user_to_closed_team_spec.js#L40
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js#L68

1. I thought in the case that there was more than one domain (just the case of the attached screenshot), however, I did not know that the error message was used in other sites, it is my first time contributing and the code can be overwhelming the first time you see it, I'm going to check which other sites it is used on, but the solutions that come to mind are:

- Keep two different messages to handle these cases in singular and plural (maybe the best option)
- Write a message in such a way that it is correct for both singular and plural. Here if I need a little help because my English is not my first language and I could make spelling mistakes.

What do you think?

2. You are right and I actually made these changes, but I didn't know if I had to do a PR on each repository and link it to the same issue.

2020-10-18 06:59 UTC, reflog requested changes
I'm not sure this change is improving the grammar here (though I might be wrong, pinging @justinegeffen ). There could be several addresses, thus the use of plural

2020-10-20 13:30 UTC, ashishbhate commented
I checked on the team invite screen, its good there:

![image](https://user-images.githubusercontent.com/1779129/96592822-6e86ed80-1306-11eb-83a7-f981252d3496.png)

2020-10-20 22:43 UTC, y-martinez commented
@ashishbhate @reflog  You are right, I already saw what the problem is, but in this case what I thought is to have two types of messages, one in the plural and the other in the singular. What do you think?

2020-10-22 11:20 UTC, ashishbhate commented
Yep, I think depending on where the error messaged is used we might want to use a different message. I think the i18n strings support variations for singular and plural forms (`one` and `other` keys).

I'll defer to @justinegeffen and @esethna

2020-10-22 14:10 UTC, justinegeffen commented
> Yep, I think depending on where the error messaged is used we might want to use a different message. I think the i18n strings support variations for singular and plural forms (`one` and `other` keys).
> 
> I'll defer to @justinegeffen and @esethna

Thanks, @ashishbhate! AFAIK, the i18n strings do support variation for singular and plural; I've definitely made a similar change in the past. 

WRT this specific change, grammatically it is correct but functionally it may be best to retain the original message and then add this one to cover singular and plural. However, this does require consultation with the various maintainers of the translations to confirm when the change can be made across the board. 

Hope this helps somewhat!

2020-10-23 06:24 UTC, justinegeffen commented
I'm 5/5 for having a singular and a plural string. @wget, is it best to post this in the i18n channel or just raise a Jira issue for the rest of the strings to be translated?

2020-10-23 14:37 UTC, y-martinez commented
> I'm 5/5 for having a singular and a plural string. @wget, is it best to post this in the i18n channel or just raise a Jira issue for the rest of the strings to be translated?

So what can I do while making that decision?

2020-10-25 12:09 UTC, wget commented
@justinegeffen It's basically up to you ^^. But when publishing an issue on Jira and removing it from GitHub, it basically becomes invisible for the community used to use GitHub. So if it were to be moved, just do it with care with proper links to keep the discussion going :)

From my experience, we have more developer feedback on GitHub instead of leading a discussion on the Mattermost community instance. But that's just my view.

For this particular case, we have the issue a bit everywhere in the source code. This issue is part of a larger issue I have been describing from the start: developers shoul**n't** tokenize strings :) e.g. [PR#4929](https://github.com/mattermost/mattermost-webapp/pull/4929)

2020-10-30 13:13 UTC, srkgupta commented
> 2\. The webapp has end to end (e2e) cypress tests that will need to be updated as well:
> 
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js#L324
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/invite_user_to_closed_team_spec.js#L40
> * https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js#L68

HI @y-martinez 

Any updates on this change requested by @ashishbhate. Can you please create a separate PR on mattermost-webapp with this change and then merge the 2 PRs together when they are finally approved. The rest of the changes in this PR looks good.

2020-10-30 15:53 UTC, y-martinez commented
Hi! @srkgupta I don't make these change because I didn't know if I need to have the approval of the new message in plural, that is, all the discussion that @reflog @justinegeffen @wget had, so for that reason I asked that in the meantime what could I do :(

2020-10-30 16:39 UTC, srkgupta commented
Oops sorry to jump in so early @y-martinez. I will let you wait once the final decision is made on this. Thanks.

2020-11-10 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-11 17:13 UTC, jfrerich commented
@reflog @justinegeffen @wget, could one of you help to ensure @y-martinez has direction on next steps?  Thanks!

2021-03-23 21:23 UTC, y-martinez commented
There are any updates of this :-/

2021-05-14 16:54 UTC, justinegeffen commented
> There are any updates of this :-/

Sorry for the delay, @y-martinez! I've assigned myself to this PR and will review it next week. :)

2021-08-07 19:01 UTC, justinegeffen commented on i18n/en.json
> +    "translation": "The email address you entered does not belong to an accepted domain: {{.Addresses}}. Please contact your System Administrator for details."
```suggestion
    "translation": "The email address you entered does not belong to an accepted domain: {{.Addresses}}. Please contact your System Admin for details."
```

2021-08-07 19:01 UTC, justinegeffen commented on i18n/nl.json
> +    "translation": "The email address you entered does not belong to an accepted domain: {{.Addresses}}. Please contact your System Administrator for details."
```suggestion
    "translation": "The email address you entered does not belong to an accepted domain: {{.Addresses}}. Please contact your System Admin for details."
```

2021-08-07 19:05 UTC, justinegeffen commented
I've re-reviewed this and I think it would be best to have a singular string and a plural string - so basically retain the previous one and add the new one. In terms of i18n work, I recommend joining the [i18n - Localization](https://community-daily.mattermost.com/core/channels/localizatio) channel and getting feedback from the maintainers. But as far as the wording goes, it looks good to me.

2021-08-07 19:06 UTC, justinegeffen commented
So basically you'd have:

"The email address you entered does not belong to an accepted domain: {{.Addresses}}. Please contact your System Admin for details."

and

"The email addresess you entered do not belong to an accepted domain: {{.Addresses}}. Please contact your System Admin for details."

2021-09-02 19:57 UTC, esethna commented
@y-martinez are you still working on this?

2022-11-03 18:33 UTC, justinegeffen commented
Following up on this to check whether it's still in flight. :)

2023-04-25 12:08 UTC, isacikgoz commented
Hi @y-martinez, big thanks for your contribution! There hasn't been recent activity on this PR so I've marked it as inactive. Following our [inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), the PR is now closed due to 30 days or more of inactivity.

However, if you're still interested working on the changes, let us know! Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420), which may require you to resubmit the changes. 

If you have any questions, don't hesitate to let us know, we're happy to help.

2023-04-25 12:08 UTC, closed without merging