License Agreement and Documentation added
mattermost/mattermost-server pull request #16048
Opened 2020-10-21 06:46 UTC by kaiwalyakoparkar

#### Summary
Required changes are done in the readme file & Licence file. The year and the owner information was missing from the license agreement so Added that information and also added this license agreement in the readme.md file.

#### Release Note

```release-note
None
```

2020-10-21 06:46 UTC, mattermod commented
Hello @kaiwalyakoparkar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-10-21 06:50 UTC, kaiwalyakoparkar commented
/check-cla

2020-10-25 19:59 UTC, jasonblais commented
@kaiwalyakoparkar thank you for your interest contributing! However, we won't be able to accept these changes:

1. The Apache 2.0 license itself should be left unmodified per legal advice. Modifying the example text will cause it to not be recognized as Apache 2.0 by a large number of license file identifiers. Instead, we include the appropriate copyright year and author (Mattermost) at the top of each source file in the repository. You can see comparable discussion in the Kubernetes repository: https://github.com/kubernetes/kubernetes/pull/65 https://github.com/kubernetes/kubernetes/pull/37305
2. Including part of the LICENSE file in the README.md may be confusing and omit critical information that conflicts with the license file itself. Thus, we prefer to simply refer users to the LICENSE file for the exact license text.

Let me know if you have any questions, and thanks for taking the time to contribute to Mattermost.

2020-10-26 04:48 UTC, kaiwalyakoparkar commented
@jasonblais please check now, I have updated my PR with some changes. Thanks for letting me know the rules of the apache license.

2020-10-26 22:24 UTC, jasonblais commented
Thank you @kaiwalyakoparkar!

GitHub did recently make it easier to find the license file for a repository, so I'm leaning towards not adding a link to the README since it would be repetitive.

![image](https://user-images.githubusercontent.com/13119842/97234984-50166b80-17b8-11eb-90fa-700bc817bd06.png)

What do you think?

2020-10-27 04:05 UTC, kaiwalyakoparkar commented
Thankyou @jasonblais ,
According to me whenever a person goes through the readme file that time he does not pay attention to the side pane. Also when we scroll down to read the readme file that time this feature hides/scrolls up. That's the reason I want to add this change so that the reader/ user gets it in the documentation part itself and does not have to search for it separately. Also many times they forget to read it and it may cause a blunder. I hope my thoughts are clear. What do you think?

2020-10-28 23:53 UTC, jasonblais requested changes
@kaiwalyakoparkar I'm good with that use case, thank you! I'm proposing a small rewording, given "license agreement" may refer to the Enterprise Edition License agreement of the commercial version (https://mattermost.com/pricing/).

2020-10-28 23:53 UTC, jasonblais commented on README.md
> +To read the license agreement visit [here](https://github.com/mattermost/mattermost-server/blob/master/LICENSE.txt)
```suggestion
See the [LICENSE file](https://github.com/mattermost/mattermost-server/blob/master/LICENSE.txt) for license rights and limitations.
```

2020-10-29 04:01 UTC, kaiwalyakoparkar commented on README.md
> +See the [LICENSE file](LICENSE.txt) for license rights and limitations.
@jasonblais I have changed the text as asked by you also I have shortened the URL to the license agreement file

2020-10-29 04:02 UTC, kaiwalyakoparkar commented on README.md
> +See the [LICENSE file](LICENSE.txt) for license rights and limitations.
@jasonblais please let me know if the shortened URL will work or I may change it to a full link

2020-10-29 11:27 UTC, jasonblais approved these changes
Looks good to me, thank you!

2020-10-29 11:27 UTC, jasonblais commented
/update-branch

2020-10-31 07:52 UTC, jespino approved these changes

2020-11-01 20:50 UTC, wiersgallak approved these changes

2020-11-01 22:17 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-11-02 12:34 UTC, hanzei commented
/update-branch

2020-11-02 22:41 UTC, hanzei commented
/update-branch

2020-11-03 19:35 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-11-03 19:37 UTC, mattermod commented
Trying to auto merge this PR.

2020-11-03 19:37 UTC, mattermod commented
Pull Request successfully merged
SHA: fb9c2faa1a93ceb22ebbcd151eaf51fb56801513

2020-11-03 19:37 UTC, merged

2020-11-03 19:37 UTC, jasonblais commented
Thanks @kaiwalyakoparkar for the contribution!