Add golang migrate migrations
mattermost/mattermost-server pull request #16055
Opened 2020-10-22 15:52 UTC by jespino

#### Summary
Add golang migrate migrations proof of concept

2020-10-22 15:52 UTC, mattermod commented
The file `Makefile` is in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2020-10-22 15:53 UTC, mattermod commented
The file `Makefile` is in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2020-10-22 15:54 UTC, mattermod commented
The file `Makefile` is in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2020-10-26 17:13 UTC, agnivade requested changes
This is more or less exactly what is done for mattermod which is okay. I'll also request a CLI command to run backward migrations as we did here: https://github.com/mattermost/mattermost-mattermod/blob/master/cmd/migrator/main.go. Without that it's not possible to leverage the down files.

But most importantly, without the actual sql files, this does not kick in yet. We need to discuss and decide on a minimum version before which we will not support upgrading to this version. Then convey that decision to PM and release management. And then finally write the sql migration code to actually run the migrations all the way from that version to latest.

That's the biggest thing.

2020-10-26 17:13 UTC, agnivade commented on store/sqlstore/migrate.go
> +	pgmigrations "github.com/mattermost/mattermost-server/v5/store/sqlstore/migrations/postgres"
Make these 3 into a separate import group in the 2nd position.

2020-10-26 17:13 UTC, agnivade commented on store/sqlstore/migrate.go
> +func (ss *SqlSupplier) Migrate() error {
A godoc here would be nice.

2020-11-19 16:42 UTC, mattermod commented
The file `Makefile` is in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2020-11-19 16:46 UTC, jespino commented
@agnivade I applied the proposed changes.

2020-11-19 16:46 UTC, mattermod commented
The file `Makefile` is in the blocklist for external contributors. Hence, these changes are not tested by the CI pipeline active until the build is re-triggered by a core committer or the PR is merged. Please be careful when reviewing it.
/cc @mattermost/core-security @mattermost/core-build-engineers

2020-11-20 06:09 UTC, agnivade commented
Nice. POC looks good.

2020-12-07 17:38 UTC, grundleborg reviewed
@jespino this looks great to me. What are the next steps, an which of them are you willing to take vs. needing the Server Team to handle?

2020-12-07 18:40 UTC, jespino commented
Probably, the next step is to decide if this is what we want to move forward, see the missing pieces (commands that cloud team needs, like the db upgrade/db downgrade), and schedule a date to start using it instead of the previous existing approach. I would say, validation of the approach during the next server meeting. If nothing changes about the approach, scheduling the merge date and properly announce it (to not collide with anything done for the next version). Once is merge, the Cloud team should be able to add the commands that they need (they can start working before branching from migrations system PR).

2020-12-07 18:42 UTC, jespino commented
//cc @grundleborg @ethervoid :point_up:

2020-12-17 09:30 UTC, ethervoid approved these changes
PoC looks good to me

2020-12-17 09:30 UTC, ethervoid commented on store/sqlstore/upgrade.go
> +	err = sqlStore.Migrate()
Maybe we can check if the system is using the new versioning so that means we can skip the old migrations. What do you think?

2021-02-26 06:45 UTC, jespino commented
Done by other PR :tada:

2021-02-26 06:45 UTC, closed without merging