MM-30005: Require manage_system to patch system_admin role.
mattermost/mattermost-server pull request #16096
Opened 2020-10-27 15:00 UTC by mkraft

#### Summary

Requires `manage_system` permission to patch `system_admin` role.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30005

#### Release Note

```release-note
Fixed a security vulnerability where granting the permission "sysconsole_write_user_management_permissions" allowed a role to edit the system_admin role.
```

2020-10-27 15:36 UTC, sbishel approved these changes

2020-10-28 07:11 UTC, jupenur approved these changes

2020-10-28 16:01 UTC, thefactremains approved these changes

2020-10-29 16:14 UTC, srkgupta requested changes
Hi @mkraft 
Although this is now handled for system_admin role, a user with sysconsole_write_user_management_permissions is still allowed to modify multiple other internal roles in the system, for example, try for system_manager/system_user_manager role. Since these roles are internal roles, the user should not be allowed to modify them. The user can escalate the system roles permissions using this. Can you please fix it across all the system roles as well.

2020-12-10 11:48 UTC, srkgupta approved these changes
Tested and the issue is fixed now and is working fine. Approving the PR.

2020-12-16 00:06 UTC, mkraft commented
/update-branch

2020-12-16 18:01 UTC, merged