Linkedin,Facebook links updated in mattermost-server
mattermost/mattermost-server pull request #16186
Opened 2020-11-01 01:41 UTC by drraghavendra

#### Summary

#### Ticket Link

#### Release Note

```release-note
```

2020-11-01 01:42 UTC, mattermod commented
Hello @drraghavendra,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-11-02 12:16 UTC, hanzei requested changes

2020-11-02 12:16 UTC, hanzei commented on DRY up the codebase
> +Welcome new contributors!
Would you please remove these unrelated changes?

2020-11-03 12:25 UTC, hanzei approved these changes
LGTM :+1:

2020-11-14 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-18 21:00 UTC, jfrerich commented on README.md
> +- **linkedin** - Follow [Mattermost](https://www.linkedin.com/company/mattermost/)
```suggestion
- **Facebook** - Follow [Mattermost](https://www.facebook.com/MattermostHQ)
- **Linkedin** - Follow [Mattermost](https://www.linkedin.com/company/mattermost/)
```

4/5 suggest we capitalize the first letters, to match the other listings.  cc @jasonblais what do you think?

2020-11-19 00:06 UTC, jasonblais approved these changes
I updated the capitalization, approving. Thank you for the contribution!

2020-11-19 00:11 UTC, jasonblais commented
/update-branch

2020-11-19 03:35 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-11-19 03:45 UTC, mattermod commented
Trying to auto merge this PR.

2020-11-19 03:45 UTC, mattermod commented
Pull Request successfully merged
SHA: 537b5a5b677b57fc982244f74a72ada26ca53284

2020-11-19 03:45 UTC, merged

2020-11-19 04:13 UTC, jasonblais commented
@drraghavendra thank you for the contribution!

2021-08-23 05:54 UTC, drraghavendra commented
sir @jasonblais PR is   hacktoberfest accepted check details here  https://github.com/mattermost/mattermost-webapp/pull/6916

2021-08-23 11:37 UTC, jasonblais commented
Thanks, I added the `hacktoberfest-accepted` label :+1:

2022-01-04 06:59 UTC, drraghavendra commented
Respected Sir @jasonblais as per the inference provided earlier,I guess Goodies are to provided for this Pull Request.

2022-01-04 12:51 UTC, jasonblais commented
Hi @drraghavendra, if you didn't receive a thank you gift from us for your contribution, please email us at community[at]mattermost.com. It is possible it didn't reach you due to shipping delays over the pandemic.