Allow 'mmctl channel move' to move private channels
mattermost/mattermost-server pull request #16433
Opened 2020-12-01 13:41 UTC by Leats

#### Summary

Currently `mmctl channel move someotherteam teamname:channelname` does not allow moving private channels. The error message only mentions direct message and group message channels that cannot be moved:
https://github.com/mattermost/mattermost-server/blob/15037a510a5da29bf16badb5ae4e6c69ee6fe946/i18n/en.json#L339-L340
While not being able to move direct message and group message channels makes sense, the same should not apply to private channels.

#### Ticket Link

None

#### Release Note

```NONE
```

2020-12-01 13:41 UTC, mattermod commented
Hello @Leats,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-01 14:39 UTC, ThiefMaster approved these changes
Very useful fix! I had to make a channel temporarily public. move it, and then make it private again as a workaround (ugly, because in theory this could leak data if someone managed to join just in that moment), and the old `mattermost channel move ...` command did not have this problem either.

2020-12-09 09:36 UTC, streamer45 approved these changes
Thank you @Leats.

Changes look good to me. I am just not sure if this was an overlook or if there was a reason to limit this to public channels only. Will defer to @mgdelacroix on that.

2020-12-20 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-04 17:14 UTC, jfrerich commented
@mgdelacroix, ping for review (and welcome back from the holiday break)

2021-01-18 08:46 UTC, mgdelacroix reviewed
Thanks a lot for the contribution, @Leats! The change LGTM, I would only like to increase the test coverage.

Would you be open to add test cases for `Should fail to move channel due to a member not member of target team` and `Should be able to (force) move channel by a member that is not member of target team` with a private channel? Both exist already in the same test function for public channels.

2021-01-19 13:12 UTC, Leats commented
> Would you be open to add test cases for `Should fail to move channel due to a member not member of target team` and `Should be able to (force) move channel by a member that is not member of target team` with a private channel?

Thank you! Yes, I can add that as well! ☺️

2021-01-30 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-02-03 21:55 UTC, emilyacook commented
> This PR has been automatically labelled "stale" because it hasn't had recent activity.
> A core team member will check in on the status of the PR to help with questions.
> Thank you for your contribution!
> 

Hey @Leats! Let me know if there is any update on this :)

2021-02-07 14:37 UTC, Leats commented
Hello @emilyacook @mgdelacroix! 
Very sorry for the wait, my move took longer than expected. I added the tests as requested, I hope everything is alright! :)

2021-02-08 10:07 UTC, mgdelacroix requested changes
Thanks for adding the tests @Leats! Added a couple of small changes

2021-02-08 10:07 UTC, mgdelacroix commented on api4/channel_test.go
> +		_, resp = th.SystemAdminClient.MoveChannel(privateChannel.Id, team2.Id, false)
```suggestion
		_, resp = client.MoveChannel(privateChannel.Id, team2.Id, false)
```

2021-02-08 10:07 UTC, mgdelacroix commented on api4/channel_test.go
> +		newChannel, resp := th.SystemAdminClient.MoveChannel(privateChannel.Id, team2.Id, true)
```suggestion
		newChannel, resp := client.MoveChannel(privateChannel.Id, team2.Id, true)
```

2021-02-08 16:20 UTC, Leats commented
Thank you, @mgdelacroix! I changed the code as requested and added the same behaviour to the local channel move so it's consistent with my previous changes (and lets the tests run through).

2021-02-09 09:24 UTC, mgdelacroix approved these changes
Thanks a lot @Leats! LGTM!! :+1:

2021-02-09 10:17 UTC, lindy65 commented
Hi @mgdelacroix - Can you link me to the Jira ticket for this PR please? Thanks :)

2021-02-09 10:20 UTC, ThiefMaster commented
I don't think there is one for it - it's just an annoying issue we discovered on our Mattermost instance when moving channels for a user, so I suggested @Leats that sending a PR for this would be a nice contribution.

2021-02-09 10:22 UTC, lindy65 commented
Thanks @ThiefMaster - QA requires a Jira ticket to move the PR through the process so wondering whether you'd like to create one? :)

2021-02-09 10:24 UTC, ThiefMaster commented
I don't think people who aren't mattermost staff can do that, can they?

> You do not have permission to create issues in this project.

2021-02-09 10:51 UTC, lindy65 commented
Ah, you're correct @ThiefMaster - non-staff can view Jira tickets only.  So @mgdelacroix will need to help us out here :)

2021-02-10 07:09 UTC, lindy65 commented
Hi @mgdelacroix :) I've created a [jira ticket](https://mattermost.atlassian.net/browse/MM-32746) for this PR. Please help fill in QA test steps and description?  TIA 👍

2021-02-10 09:31 UTC, mgdelacroix commented
Thanks @lindy65!! done :)

2021-02-10 11:38 UTC, lindy65 approved these changes
Thanks @Leats - looks good to me.  Testing will be done after merge 👍

2021-02-11 16:26 UTC, merged