MM-32018 update URL endpoint for DownloadComplianceReport function
mattermost/mattermost-server pull request #16700
Opened 2021-01-14 20:04 UTC by maxerenberg

#### Summary
This pull request fixes the DownloadComplianceReport method in the golang client so that a full report is downloaded, not just the metadata.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32018

#### Release Note
```release-note
The DownloadComplianceReport function in the golang driver has been fixed to download
a full report as a zip archive.
```

2021-01-14 20:04 UTC, mattermod commented
Hello @maxerenberg,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-15 00:32 UTC, sbishel requested changes
Nice find....

2021-01-15 00:32 UTC, sbishel commented on model/client4.go
> +}
I see you followed the pattern used in the above function, but let's update both `GetComplianceReportDownloadRoute` and `GetComplianceReportRoute` to use `GetComplianceReportsRoute`.

2021-01-18 17:03 UTC, sbishel approved these changes

2021-01-26 22:29 UTC, furqanmlk approved these changes
Test cases passed
Golang client working as expected

![image](https://user-images.githubusercontent.com/6909890/105914221-07ab5b80-5ffc-11eb-8757-b327235f8458.png)

2021-01-27 14:06 UTC, merged

2021-01-27 15:25 UTC, amyblais commented
@maxerenberg @mkraft It seems this missed a second dev review - please see the process here https://developers.mattermost.com/contribute/getting-started/code-review/.

2021-01-27 16:32 UTC, maxerenberg commented
My apologies. I'll make sure to check the Code Review process for next time.