removed redundant CreateMembershipIfNeeded call
mattermost/mattermost-server pull request #17044
Opened 2021-03-02 09:32 UTC by reflog

#### Summary
A potential race was being caused by a redundant call to CreateMembershipIfNeeded .

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-33396

#### Release Note

```release-note
NONE
```

2021-03-02 13:30 UTC, streamer45 approved these changes
Nice :+1:

2021-03-03 05:23 UTC, agnivade requested changes
@reflog - Sorry for not having any prior context on this, but can you please explain what exactly is the race here in the PR message?

Can we also add a test for this?

2021-03-03 07:44 UTC, streamer45 commented
> @reflog - Sorry for not having any prior context on this, but can you please explain what exactly is the race here in the PR message?

@agnivade 

This was spotted during load-tests. The logs were getting filled with "duplicate entries" warnings on inserting `ThreadMembership` rows. It turned out there were two subsequent calls (one of which in a separate goroutine) triggered by `handlePostEvents`. That's where the race originated from. Since we are making db calls it didn't have any real side-effect other than causing a spam of logs (and possibly a few more queries).

2021-03-03 07:45 UTC, reflog commented
> 
> 
> > @reflog - Sorry for not having any prior context on this, but can you please explain what exactly is the race here in the PR message?
> 
> @agnivade
> 
> This was spotted during load-tests. The logs were getting filled with "duplicate entries" warnings on inserting `ThreadMembership` rows. It turned out there were two subsequent calls (one of which in a separate goroutine) triggered by `handlePostEvents`. That's where the race originated from. Since we are making db calls it didn't have any real side-effect other than causing a spam of logs (and possibly a few more queries).
☝🏻 
What Claudio said :)

2021-03-03 14:59 UTC, agnivade commented on app/post.go
It seems like there is some difference in the two. This query wouldn't be executed if `ThreadAutoFollow` is set to false and if it's a root post. Whereas the other one will be executed always, along with the `ThreadAutoFollow` passed to it. 

I guess the end result is the same, but I am wondering if we should add the if condition to whichever query we are keeping?

2021-03-04 14:01 UTC, reflog commented
@agnivade @streamer45 - I am closing this PR in favor of https://github.com/mattermost/mattermost-server/pull/17068 since both Agniva's comment was a correct one and there were other minor changes.

2021-03-04 14:01 UTC, closed without merging