Update split SDK to 6.0.2 to fix sync bug
mattermost/mattermost-server pull request #17060
Opened 2021-03-03 17:57 UTC by jwilander

#### Summary
Update the split.io SDK to fix a synchronization issue https://github.com/splitio/go-client/issues/130

#### Release Note

```release-note
None
```

2021-03-03 18:00 UTC, crspeller requested changes
I think you need to run `go mod vendor` and `go mod tidy`

2021-03-03 18:00 UTC, jwilander commented
I sure do. Been a while since I update submitted a PR to update a dependency :P

2021-03-03 18:36 UTC, crspeller approved these changes

2021-03-04 16:15 UTC, streamer45 approved these changes

2021-03-04 16:16 UTC, merged