[MM-34838] Remove Ancillary Permissions That Are Purposefully Being Removed
mattermost/mattermost-server pull request #17405
Opened 2021-04-14 19:00 UTC by hahmadia

#### Summary

If I have a section permission that gives me ancillary permissions, I cannot remove an ancillary permission individually via MMCTL anymore. This PR aims to resolve this issue.

For example. 
I have SYSCONSOLE_XXXX_WRITE which gives me `manage_team` permission, if I try to remove `manage_team`, it will always keep being re-added.

Discussion started here
https://github.com/mattermost/mattermost-server/pull/16917#discussion_r612743973

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34838

#### Release Note

```release-note
None
```

2021-04-14 19:01 UTC, hahmadia commented
Please note that tests are on the way. I've just added you guys to get a look ahead of time.

2021-04-16 13:16 UTC, mkraft requested changes

2021-04-16 13:16 UTC, mkraft commented on model/role.go
> +// This function removes any ancillary permissions that user has removed from their new Permissions without having removed the sub-section permission
Also, this isn't really *removing* ancillary permissions. It's doing some set operations. As far as I can tell it's doing...

* Let *O* be the old permissions.
* Let *N* be the new permissions.
* Let *A* be the subset of *N* that are ancillary.

`RemoveUnwantedAncillaryPermissions` = (*N* - *O*) ⋃ *A*

Can this be simplified to: *N* - *A*?

I may be totally wrong. Let me know.

2021-04-19 13:20 UTC, amyblais commented
@hahmadia v5.35 will be based on Cloud April 21st release which is coming on Wednesday. Is this and the other bug fixes still on track?

2021-04-19 15:17 UTC, hahmadia commented
/update-branch

2021-04-20 15:10 UTC, closed without merging