[MM-29666] compliance export skipped posts
mattermost/mattermost-server pull request #17445
Opened 2021-04-19 14:43 UTC by maxerenberg

#### Summary
This PR fixes a bug in the compliance export which causes some posts to be skipped when they have the same timestamp.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29666

#### Release Note
```release-note
NONE
```

#### Enterprise PR
https://github.com/mattermost/enterprise/pull/977

2021-04-19 14:45 UTC, maxerenberg commented
This cause of the bug was the exact same problem we were having in https://github.com/mattermost/mattermost-server/pull/17185 - we assumed that timestamps are unique for each post, which they are not.

2021-04-20 23:26 UTC, sbishel requested changes

2021-04-21 13:32 UTC, maxerenberg commented on jobs/jobs_watcher.go
> +					panic("Couldn't send job to worker")
Whoops! Yes, this was left over from debugging.

2021-04-21 15:56 UTC, sbishel approved these changes

2021-04-26 15:40 UTC, mkraft approved these changes

2021-04-29 05:15 UTC, agnivade commented
Great work with this! I think you have solved our Message reliability problem with this query :laughing: 

Although, we need to be careful with this one. This is effectively the same as https://github.com/mattermost/mattermost-server/pull/16527, which does a two-column ordering, and due to that the query performance dropped drastically (https://github.com/mattermost/mattermost-server/pull/16527#discussion_r553928532).

And that is precisely why that PR got paused. Message export performance is important to a lot of customers.

Ideally, I'd like to see the query fixed, and the performance remain the same. That needs cleaning up redundant indexes, and adding new ones I believe. Which means writing asynchronous one-off scripts to add/remove indexes that the customers can run before upgrading Mattermost. But if this needs to go in urgently, that's okay too. Just that we all need to be aware of the tradeoffs.

2021-04-29 19:40 UTC, furqanmlk reviewed
**Following scenarios are failing** 
Scenario 01:
1. Create 50 posts with slash command
2. Create 5 posts using API with same timestamp
3. Run Compliance Export
4. It exports only 50 posts that were posted using slash command, it does not export posts from API with same time stamp
Note: API posts are in Datebase and are shown in Channels.

Scenario 02 : Any post by API is not being exported

2021-05-04 13:08 UTC, merged