Fixed MM-33249 issue
mattermost/mattermost-server pull request #17475
Opened 2021-04-21 14:19 UTC by manojmalik20

#### Summary
Fixed MM-33249 Mobile > Unable to set custom status emoji via slash command

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33249

#### Release Note
```release-note
Added the logic for detecting Unicode emoji and setting it as custom status emoji via slash commands.

2021-04-21 14:19 UTC, mattermod commented
Hello @manojmalik20,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-04-21 14:33 UTC, manojmalik20 commented
/check-cla

2021-04-23 13:42 UTC, hmhealey requested changes
The code looks good, but would you mind adding some unit tests for the emoji detection logic? I think it would be good to have tests for the Unicode case as well as some more difficult cases like multi-part family emojis and messages containing Unicode emojis. Perhaps you could pull out the whole block for constructing the `CustomStatus` into its own function to simplify that testing since it would just take a string and return a `CustomStatus`.

2021-04-26 13:20 UTC, manojmalik20 commented
While going through the SystemEmojis map in `emojiData.go`, I noticed that multiple emoji names contain same unicode. For eg-
`man_singer_medium_skin_tone`, `man_teacher_medium_skin_tone`, `family_man_woman_girl_boy_medium_skin_tone`.. and many more have the same unicode `1f468-1f3fd`... so does it mean that the SystemEmojis map is wrong?

2021-04-26 21:52 UTC, hmhealey commented
That is a very good find, and it's definitely a problem. The existing code doesn't actually look at those unicode values (just whether or not the emoji exists in the map), so it's never caused a problem before.

That `1f468-1f3fd` one you mentioned is "man light skin tone", so that's the only one that should have that file name. Looking at the data files in the web app, they also have the same issue where the filename is duplicated. Posting `:man_farmer_light_skin_tone:` in the web app also outputs the wrong emoji (`:man_light_skin_tone:`), so the issue is bigger than just the server's data files. I'll file a ticket to investigate that further. In the mean time, there are definitely some correct emojis with skin tones, so maybe we can find some to use for tests while we fix the data files?

Also, CCing @ethervoid since he added the generation for that file in https://github.com/mattermost/mattermost-webapp/pull/3429 in case he remembers anything about this issue. There is a comment in the `make-emojis` script about that, so that PR didn't cause the issue though.

2021-04-27 09:52 UTC, ethervoid commented
@hmhealey uf no idea, this was my first PR for MM so not a clue sorry

2021-04-27 12:06 UTC, manojmalik20 commented
@hmhealey Can you rerun the CI? I've fixed the lint errors.

2021-04-27 13:50 UTC, hmhealey commented
@ethervoid No worries. The problem seems to predate your changes since the issue appears in the webapp's emoji data as well, and I figured it was a long shot that you would remember it from that far back.

@manojmalik20 I've filed a ticket to look into the incorrect unicode values being generated for those ones. Going a bit more technical, it seems to only affect certain "job" emojis using both a skin tone modifier and a ZWJ sequence (farmer, teacher, astronaut, etc). I filed [MM-35234](https://mattermost.atlassian.net/browse/MM-35234) to look into that, but in the mean time, I wonder if there's a good way to work around that in the mean time.

Perhaps we can identify if an emoji's unicode looks like `<man/woman>_<skin tone>_200d_` and remove the skin tone modifier for the time being. It looks like since the unicode is messed up for those emojis, we're not actually generating images for the skin tone variations, so we'll have to fall back to the generic skin tone on those. That pattern should catch all the ones we know about while we fix the data file generator.

Also, that family emoji with a skin tone modifier you mentioned isn't supported. From what I can tell, families with skin tone modifiers haven't made it into an official emoji spec, so we can skip that and just test the ones with the default skin tone.

2021-04-29 07:56 UTC, manojmalik20 commented
> Perhaps we can identify if an emoji's unicode looks like `<man/woman>_<skin tone>_200d_` and remove the skin tone modifier for the time being.
@hmhealey How do you propose to implement this?

2021-04-30 13:32 UTC, hmhealey commented
Once you have the unicode as a hex string, you could try a regex to match that. I think `^(1f468|1f469)_(1f3fb|1f3fc|1f3fd|1f3fe|1f3ff)_200d_` might do it. The first group is man/woman and the second is all the skin tones.

2021-05-04 14:06 UTC, manojmalik20 commented
@hmhealey I didn't use `^(1f468|1f469)` because it doesn't cover certain emojis like `basketball_man`, `surfing_man` etc.. 
This code works with almost all emojis except some family emojis with skin tones. You can review and test it yourself.

2021-05-05 20:44 UTC, hmhealey reviewed
Maybe instead of immediately removing the skin tone, maybe we could check if we have the emoji with a skin tone first removing it? That'll give us some nice forwards compatibility when we eventually support the skin tones for those emojis.

2021-05-17 14:26 UTC, hmhealey approved these changes
Looks good to me!

2021-05-20 11:08 UTC, isacikgoz reviewed
Looks good to me overall, have some styling concerns.

2021-05-20 11:09 UTC, isacikgoz commented on app/slashcommands/command_custom_status.go
> +	if len(skinToneLocations) > 0 {
Same indentation case here.

2021-05-25 22:32 UTC, ogi-m approved these changes
LGTM 👍🏻

2021-05-26 16:22 UTC, manojmalik20 commented
@esethna Can you please add more reviewers or the `EETests` label in this PR?

2021-05-26 16:43 UTC, esethna commented
@isacikgoz can you please help with a re-review and approve and merge if your concerns have been addressed? 

@ogi-m I'm not sure how the EETests label is supposed to work? Can you help here as needed? ^

2021-05-26 18:02 UTC, isacikgoz approved these changes

2021-05-26 18:03 UTC, merged