Improving doc extraction command
mattermost/mattermost-server pull request #17482
Opened 2021-04-22 10:48 UTC by jespino

#### Summary
Improving doc extraction command

#### Release Note
```release-note
NONE
```

2021-04-22 10:48 UTC, mattermod commented on cmd/mattermost/commands/extract_content.go
> +					mlog.Error("Failed to extract file content", mlog.Err(err), mlog.String("fileInfoId", fileInfo.Id))
Gentle reminder to check our logging [principles](https://developers.mattermost.com/contribute/server/style-guide/#log-levels) before merging this change.

2021-04-22 10:59 UTC, mgdelacroix approved these changes

2021-04-22 13:11 UTC, reflog requested changes

2021-04-22 13:42 UTC, jespino commented on services/docextractor/plain.go
> +		if count > total-4 || count > len(runes)-4 {
yes, you are right, a constant there can explain the intention behind that.

2021-04-22 13:48 UTC, reflog approved these changes

2021-04-22 13:48 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-04-22 14:36 UTC, mattermod commented
Trying to auto merge this PR.

2021-04-22 14:36 UTC, merged

2021-04-22 14:36 UTC, mattermod commented
Pull Request successfully merged
SHA: 7c7c4716e6cc73878734f4b52a34800096bd39e7

2021-04-22 14:36 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-22 14:40 UTC, jespino commented
/cherry-pick cloud

2021-04-22 14:40 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-23 12:41 UTC, amyblais commented
/cherry-pick release-5.35

2021-04-23 12:41 UTC, mattermod commented
Cherry pick is scheduled.

2021-04-26 10:57 UTC, ethervoid commented
/cherry-pick cloud

2021-04-26 10:57 UTC, mattermod commented
Cherry pick is scheduled.