Fixup: app_test: use locally-instantiated search engine variable during search engine registration
mattermost/mattermost-server pull request #17718
Opened 2021-06-04 11:23 UTC by jayaddison-collabora

#### Summary
While running `mattermost-server` unit tests locally by using `make test-server-quick`, I'd run into the following Go panic:

```
panic(0x21ea6e0, 0x3987f00)
    /usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
github.com/mattermost/mattermost-server/v5/services/searchengine.(*Broker).RegisterBleveEngine(...)
    /home/jka/Documents/mattermost-server/services/searchengine/searchengine.go:23
github.com/mattermost/mattermost-server/v5/app.TestUnitUpdateConfig(0xc0026c9500)
    /home/jka/Documents/mattermost-server/app/app_test.go:46 +0x120
```

(also reported using the Mattermost community developers channel [here](https://community.mattermost.com/core/pl/x1u7rhckx3rt8j4cc8ph9sbqow))

The root cause appears to be that the `app_test` tries to register a search engine against a [nil/empty `SearchEngine` member variable](https://github.com/mattermost/mattermost-server/blob/09f99e242699c5aaf380f1076d3aa043a88853b0/app/app_test.go#L46), leading to a nil pointer dereference in [this function](https://github.com/mattermost/mattermost-server/blob/09f99e242699c5aaf380f1076d3aa043a88853b0/services/searchengine/searchengine.go#L22-L24).

The fix suggested here essentially copies a pattern found elsewhere in the codebase, in the [`app/server` module here](https://github.com/mattermost/mattermost-server/blob/09f99e242699c5aaf380f1076d3aa043a88853b0/app/server.go#L298-L304).

#### Ticket Link
N/A

#### Release Note
-->
```release-note
NONE
```

2021-06-04 11:23 UTC, mattermod commented
Hello @jayaddison-collabora,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-04 12:48 UTC, mgdelacroix requested changes
Thanks for the PR @jayaddison-collabora! :rocket: The approach looks valid, although I wonder if we should not disable this test when the `short` flag is enabled, as the searchengine is not being initialised because of the store itself not being initialised

//cc @jespino

2021-06-04 12:48 UTC, mgdelacroix commented on app/app_test.go
> +	searchEngine := searchengine.NewBroker(th.App.Config(), th.App.Srv().Jobs)
You need to import `searchengine` above

2021-06-07 10:53 UTC, jayaddison-collabora commented
@mgdelacroix @jespino FWIW - during [configuration of custom GitLab CI](https://gitlab.collabora.com/sysadmin/mattermost/mattermost-server/-/merge_requests/4), I've found that -- on the `release-5.35` branch, albeit currently a few (unrelated) commits behind at 1a0f7331fd29abf9f5b2950cd9c3927b679f5712, the following tests had issues during short tests:

- [`migrate_test`](https://github.com/mattermost/mattermost-server/blob/1a0f7331fd29abf9f5b2950cd9c3927b679f5712/config/migrate_test.go#L21) as noted here by @mgdelacroix 
- [`version_test`](https://github.com/mattermost/mattermost-server/blob/1a0f7331fd29abf9f5b2950cd9c3927b679f5712/model/version_test.go)
- Tests within the `app` module (worked around by using [this non-ideal commit](https://gitlab.collabora.com/sysadmin/mattermost/mattermost-server/-/merge_requests/4/diffs?commit_id=13b7725205d27c3cf2c6bb6b56bcd1d09f942c1a))

These issues only seem to appear within a GitLab CI runner environment (and are reproducible with `gitlab-runner` which can be handy for local development testing).

There are quite a few moving parts here and I don't feel like I have a full understanding of how they interact, but I'll try to chip away at one or two small details and provide patches where they seem correct and safe.

2021-06-11 13:10 UTC, jespino requested changes
The real problem here is, "why the searchEngine is even needed here?" actually is not, if you revmoe the search engine initialization entirely, the tests passes perfectly fine.

2021-06-11 13:18 UTC, jespino commented
@jayaddison-collabora about the migration test, it isn't using one of the autodetected setup functions for not-short test runs, instead, we have to manually exclude that test using:
```go
if testing.Short() {
       t.SkipNow()
}
```

2021-06-11 13:18 UTC, jespino approved these changes
LGTM

2021-06-14 08:55 UTC, mgdelacroix approved these changes
LGTM, thanks @jayaddison-collabora!!! :+1:

2021-06-14 08:56 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-06-14 10:20 UTC, jayaddison-collabora commented
(CircleCI seemed not to initialize for f526823; merged latest changes to bump the build)

2021-06-15 11:15 UTC, jayaddison-collabora commented
@mgdelacroix Could you try re-applying the `EETests` label when you have a moment?  I think/hope that should complete the test suite here.

2021-06-17 13:06 UTC, mgdelacroix commented
/update-branch

2021-06-17 13:07 UTC, mgdelacroix commented
I've just reenabled EETests and merged `master` in to try and relaunch the tests, hope the report makes it back this time. Apologies for the waiting @jayaddison-collabora

2021-06-17 13:40 UTC, mattermod commented
Trying to auto merge this PR.

2021-06-17 13:40 UTC, mattermod commented
Pull Request successfully merged
SHA: 030543fed97facef35be22796cb469c949b41dc1

2021-06-17 13:40 UTC, merged

2021-06-17 13:56 UTC, jayaddison-collabora commented
@mgdelacroix No problem at all, and thank you!