MM-37445 - Create config setting to always have the team sidebar visible
mattermost/mattermost-server pull request #18013
Opened 2021-07-27 16:55 UTC by liehart

#### Summary

This PR add a new configuration option `AlwaysShowTeamSidebar` with default value `true` that allow to constantly show team sidebar even the user only have one team. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37445

#### Release Note

```release-note
Added a new config setting AlwaysShowTeamSidebar
```

2021-07-27 16:55 UTC, mattermod commented
Hello @liehart,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-08-05 23:04 UTC, mickmister commented
Hi @liehart! Posting your question from https://github.com/mattermost/mattermost-server/issues/18010#issuecomment-888483776 here:

> Does this issue have to be implemented at mattermost-webapp too? For server side I have open a PR https://github.com/mattermost/mattermost-server/pull/18013. Please let me know if i did correctly. 

Yes this will also need to be implemented for `mattermost-webapp`. You can access this new config value by using a Redux selector like this https://github.com/mattermost/mattermost-webapp/blob/HEAD/components/admin_console/reset_password_modal/index.ts#L23-L28.

2021-08-05 23:08 UTC, mickmister requested changes
In order to add a new config setting, we'll have to modify a struct in `model/config.go`. Here's some documentation on how to add a new config setting https://developers.mattermost.com/contribute/server/system_console/#adding-fields-to-the-configuration.

I think this config setting should be added to the `ServiceSettings` struct.

2021-08-07 02:28 UTC, liehart commented
Actually, I have added `AlwaysShowTeamSidebar` under `ServiceSettings` struct.

2021-08-10 07:59 UTC, mickmister approved these changes
LGTM, though I'm wondering where it should appear in the order of fields. I'm not sure if the settings are usually just added to the bottom. @liehart Have you tested this via crafted API requests or began work on the web application changes? We'll use those changes to test this PR.

2021-08-11 02:51 UTC, liehart commented
Yes I've tested it with API request, now I'm working on web application. But I'm unsure where to make changes, web app have 2 team sidebar, legacy and not.

2021-08-16 19:04 UTC, hanzei reviewed
Is there an associated webapp PR?

2021-08-16 19:04 UTC, hanzei commented on model/config.go
> +		s.AlwaysShowTeamSidebar = NewBool(true)
Should this ready be enabled by default?

2021-08-17 05:20 UTC, mickmister commented
@liehart To discuss specifics of what needs to change in the webapp for this PR, do you mind asking questions to the webapp development team on our community server at https://community.mattermost.com/core/channels/webapp? Just mention this ticket, and the developers will be glad to answer your questions.

Thanks for this contribution @liehart :+1:

2021-08-25 04:22 UTC, mickmister commented
@hmhealey Do you have any input on @liehart's comment?

> Yes I've tested it with API request, now I'm working on web application. But I'm unsure where to make changes, web app have 2 team sidebar, legacy and not.

2021-08-30 14:34 UTC, hmhealey commented
@liehart If you update to the latest version of the web app, there should only be the one version of the sidebar now. We actually just removed the legacy sidebar a few weeks back.

2021-09-10 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2022-04-26 16:57 UTC, hmhealey commented
Thanks for any work you've done on this, @liehart.

Feel free to let us know if you'd still like to work on this, but otherwise, we're going to open it back up for others to work on.

2022-04-26 16:57 UTC, closed without merging