[MM-37725] - Self-managed: Update email template to new branding - Password Reset
mattermost/mattermost-server pull request #18135
Opened 2021-08-13 11:03 UTC by AGMETEOR

#### Summary
This PR updates the password reset email template to new branding

<img width="1792" alt="Screenshot 2021-08-13 at 13 59 25" src="https://user-images.githubusercontent.com/28563179/129347848-8d6f8f20-fe12-4738-96d6-dcb2736b904c.png">

#### Ticket Link
[MM-37725](https://mattermost.atlassian.net/browse/MM-37725)

#### Release Note
```release-note
NONE

```

2021-08-13 13:52 UTC, neallred reviewed
Code looks good to me aside from the comment in the [webapp side](https://github.com/mattermost/mattermost-webapp/pull/8582/files) requesting to remove the old picture.

2021-08-13 17:26 UTC, stevemudie commented
@AGMETEOR The email confirmation (when I signed up as a new user) contained the updated graphics but the password reset one didn't have any graphic in it.

<img width="623" alt="Screen Shot 2021-08-13 at 1 24 20 PM" src="https://user-images.githubusercontent.com/7083912/129396833-706fcbc4-e93a-424e-90ff-650ea59a7c08.png">

2021-08-16 10:57 UTC, AGMETEOR commented
@stevemudie this PR has a webapp part here https://github.com/mattermost/mattermost-webapp/pull/8582 where the image lives. The test server is not picking up the webapp code. We can test this post merge?

2021-08-16 11:47 UTC, pablovelezvidal commented on templates/reset_body.html
> +      color: rgba(63, 67, 80, 1) !important;
when opacity value is 100% (1), the alpha channel is not needed, so no need to use the four channels rgba function. The rgb(r, g, b) is enough.

2021-08-16 11:49 UTC, pablovelezvidal approved these changes
Besides the comment about the RGBA function, everything else looks good to me.

2021-08-16 18:13 UTC, stevemudie approved these changes
Will tests post merge due to the image not being picked up here.

2021-08-18 12:52 UTC, neallred approved these changes
LGTM. Thanks, @AGMETEOR !

2021-08-18 18:33 UTC, AGMETEOR commented
/update-branch

2021-08-18 18:43 UTC, AGMETEOR commented
/update-branch

2021-08-18 19:32 UTC, AGMETEOR commented
/update-branch

2021-08-19 22:20 UTC, andrewbrown00 requested changes
Thanks, @AGMETEOR, one item to resolve:

- [ ] We're missing the **Questions?** section below the link expires language

Current | Design
----- | -----
![image](https://user-images.githubusercontent.com/48559658/130151359-17ae3cba-84a1-4e02-8c5b-b875160a9761.png) | ![image](https://user-images.githubusercontent.com/48559658/130151774-64dd0087-1ce8-475d-abef-76c6d74820fc.png)


[Here's a link to the design file for reference](https://www.figma.com/file/TnHl6HeN0Z9n7zYXx6hS5T/MM-37612-Update-Emails-to-align-with-new-brand?node-id=522%3A60939).

2021-08-20 06:31 UTC, AGMETEOR commented
> Thanks, @AGMETEOR, one item to resolve:
> 
> * [ ]  We're missing the **Questions?** section below the link expires language
> 
> Current	Design
> ![image](https://user-images.githubusercontent.com/48559658/130151359-17ae3cba-84a1-4e02-8c5b-b875160a9761.png)	![image](https://user-images.githubusercontent.com/48559658/130151774-64dd0087-1ce8-475d-abef-76c6d74820fc.png)
> [Here's a link to the design file for reference](https://www.figma.com/file/TnHl6HeN0Z9n7zYXx6hS5T/MM-37612-Update-Emails-to-align-with-new-brand?node-id=522%3A60939).

@andrewbrown00 that’s how it works when the support email is not set from the admin console. When the support email is set, the questions section will show

2021-08-20 16:27 UTC, andrewbrown00 commented
> @andrewbrown00 that’s how it works when the support email is not set from the admin console. When the support email is set, the questions section will show

Thanks, @AGMETEOR, for providing that context. I wasn't aware of that. We could probably be consistent across the emails as a way for users to have an option to always reach us. We can revisit the UX to review and make a decision, create a separate ticket if needed.

2021-08-20 16:29 UTC, AGMETEOR commented
> > @andrewbrown00 that’s how it works when the support email is not set from the admin console. When the support email is set, the questions section will show
> 
> Thanks, @AGMETEOR, for providing that context. I wasn't aware of that. We could probably be consistent across the emails as a way for users to have an option to always reach us. We can revisit the UX to review and make a decision, create a separate ticket if needed.

We can maybe create a separate ticket

2021-08-20 16:30 UTC, andrewbrown00 approved these changes
Thanks, @AGMETEOR, changes look good 🙂 , based on the previous comment about the generic reset vs being sent from support.

![image](https://user-images.githubusercontent.com/48559658/130264726-4f700264-3710-4d72-9d9c-db9a1cc0598a.png)

2021-08-20 16:31 UTC, merged

2021-08-20 16:31 UTC, mattermod commented
Cherry pick is scheduled.

2021-08-20 16:31 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-server
   465595284..0cd711aac  MM-36387   -> upstream/MM-36387
   833339ee0..dcaca33ad  MM-37462-add-channel-split -> upstream/MM-37462-add-channel-split
   01ba0cd71..b2299d359  cloud      -> upstream/cloud
   74518ea16..f13ebe84e  master     -> upstream/master
Fetching origin
Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096
Switched to a new branch 'automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096'
Branch 'automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096' set up to track remote branch 'release-6.0' from 'upstream'.

+++ About to attempt cherry pick of PR #18135 with merge commit f13ebe84ef83c45efde088e91b9ee8bb8fbd4ea7.

[automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096 8e54123eb] [MM-37725] - Self-managed: Update email template to new branding - Password Reset (#18135)
 Author: Allan Guwatudde <guwats10@gmail.com>
 Date: Fri Aug 20 19:31:34 2021 +0300
 1 file changed, 12 insertions(+), 7 deletions(-)

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096:automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0

Failed to add the RSA host key for IP address '140.82.114.3' to the list of known hosts (/app/.ssh/known_hosts).
remote: 
remote: Create a pull request for 'automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0' on GitHub by visiting:        
remote:      https://github.com/mattermost-build/mattermost-server/pull/new/automated-cherry-pick-of-mattermost-server-%2318135-upstream-release-6.0        
remote: 
To github.com:mattermost-build/mattermost-server.git
 * [new branch]          automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0-1629477096 -> automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0

+++ Creating a pull request on GitHub at mattermost-build:automated-cherry-pick-of-mattermost-server-#18135-upstream-release-6.0
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "base"

+++ Returning you to the master branch and cleaning up.

```

2021-08-20 17:16 UTC, amyblais commented
/cherry-pick cloud

2021-08-20 17:16 UTC, mattermod commented
Cherry pick is scheduled.