Translations update from Weblate
mattermost/mattermost-server pull request #18420
Opened 2021-09-20 07:03 UTC by weblate

Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_master/) for mattermost-languages-shipped/mattermost-server.

Current translation status:

![Weblate translation status](https://translate.mattermost.com/widgets/mattermost/-/mattermost-server_master/horizontal-auto.svg)

2021-09-20 16:35 UTC, puerco requested changes

2021-09-20 16:35 UTC, puerco commented on i18n/es.json
> +    "translation": "El texto introducido supera el límite de caracteres. La cabecera del canal está limitada a {{.MaxLength} caracteres."
It seems the bot sent a string with an invalid templating substitution:
```suggestion
    "translation": "El texto introducido supera el límite de caracteres. La cabecera del canal está limitada a {.MaxLength} caracteres."
```

2021-09-21 14:25 UTC, puerco commented on i18n/es.json
> +    "translation": "El texto introducido supera el límite de caracteres. La cabecera del canal está limitada a {{.MaxLength} caracteres."
Fixed in weblate :+1:

2021-09-21 14:25 UTC, puerco commented
/release-note-none

2021-09-21 14:39 UTC, cpanato approved these changes

2021-09-21 14:40 UTC, puerco approved these changes

2021-09-21 14:40 UTC, merged