add support to store users recent emojis in user.props
mattermost/mattermost-server pull request #19398
Opened 2022-01-23 13:46 UTC by darkLord19

Fixes #18603

2022-01-23 13:46 UTC, mattermod commented
Hello @darkLord19,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-01-24 19:27 UTC, esethna commented
Thanks @darkLord19! To clarify, is this storing recently used emoji or "most frequently used" emoji based on logic?

2022-01-24 19:30 UTC, darkLord19 commented
@esethna it stores recently used emojis with their usage count. And then we render in the decreasing order of the usage count. This is as per my discussion with @hmhealey

2022-01-24 19:42 UTC, esethna approved these changes

2022-01-24 19:42 UTC, esethna commented
@darkLord19 great, thanks!

@jgilliam17 FYI this should be tested with the webapp PR

2022-01-25 22:35 UTC, hmhealey requested changes
Glad to see this finally coming together!

One problem with this though is that `User.Props` actually isn't the correct spot for this since that field is more used for things that have to be accessible to other users. These should actually be stored in the `Preferences` table since that's where private settings and such for the user should be stored. Does that make sense?

Good/bad news with that though is that the `Preferences` table is designed to store any sort of data so it doesn't need server changes to accomplish that though.

2022-01-25 22:35 UTC, hmhealey commented on api4/status.go
> +	api.BaseRoutes.User.Handle("/recentEmojis", api.APISessionRequired(updateUserRecentEmojis)).Methods("PUT")
I'm double checking with a server team, but I think the naming convention for this API might be `/recent_emojis`. I asked [here](https://community-daily.mattermost.com/core/pl/bxq6yh4guib9djr3cecttw6fby) on community

2022-02-01 16:11 UTC, closed without merging

2022-02-01 16:11 UTC, darkLord19 commented
changed approach for feature which now requires only webapp changes so closing this