add feature flag
mattermost/mattermost-server pull request #19446
Opened 2022-01-28 22:22 UTC by neallred

#### Summary

#### Ticket Link

#### Release Note

```release-note

```

2022-02-02 20:52 UTC, mattermod commented
Failed running enterprise tests. @mattermost/core-build-engineers have been notified. Error:  
```500: An internal server error occurred.```

2022-02-11 19:46 UTC, mickmister approved these changes
LGTM :tada:

2022-02-11 19:46 UTC, mickmister commented on app/migrations.go
> +// putthing the first admin through onboarding shouldn't be very disruptive
```suggestion
// arbitrary choice, though if there is an longstanding installation with less than 10 messages,
// putting the first admin through onboarding shouldn't be very disruptive
```

2022-02-14 13:40 UTC, Willyfrog commented
@hanzei can you please prioritize reviewing this PR as it is part of the Growth Spike?

2022-02-14 13:48 UTC, hanzei requested changes
Thanks for continuing my PR :+1: 

A few comments below

2022-02-14 13:48 UTC, hanzei commented on api4/system.go
> +	}
Let's keep all the business logic in the `app` layer and move code into `app.CompleteOnboarding`

2022-02-14 13:48 UTC, hanzei commented on api4/system.go
>  	api.BaseRoutes.System.Handle("/onboarding/complete", api.APIHandler(completeOnboarding)).Methods("POST")
I forgot to add the session handler as part of my PR. Mind adding it here?

```suggestion
	api.BaseRoutes.System.Handle("/first_admin_setup", api.APISessionRequired(getFirstAdminCompleteSetup)).Methods("GET")
	api.BaseRoutes.System.APISessionRequired("/onboarding/complete", api.APIHandler(completeOnboarding)).Methods("POST")
```

2022-02-14 13:48 UTC, hanzei commented on api4/system.go
>  	api.BaseRoutes.System.Handle("/onboarding/complete", api.APIHandler(completeOnboarding)).Methods("POST")
2/5 that the API endpoints should be more similar. It note clear a the reader that they belong to the same feature. Maybe we simplify to `/onboarding` `POST` and `GET`?

2022-02-14 13:48 UTC, hanzei commented on api4/system.go
> +	}
0/5 should this be it's own store method? Or at least an `app` method

2022-02-15 18:58 UTC, hanzei approved these changes
LGTM :+1:

2022-02-15 18:58 UTC, hanzei commented on app/migrations.go
> +// putting the first admin through onboarding shouldn't be very disruptive
```suggestion
// putting the first admin through onboarding shouldn't be very disruptive.
```

2022-02-15 18:58 UTC, hanzei commented
/update-branch

2022-02-15 23:46 UTC, merged