MM-42345: Include stdlog level in default mlog config
mattermost/mattermost-server pull request #19722
Opened 2022-03-07 15:52 UTC by wiggin77

#### Summary
During server startup, the std lib logger is redirected to mlog to capture any logging from third-party libraries.  These log records are emitted using a specific log level so that they can be output to specific log targets, mixed with MM logs or separated.

It was intended this log level be included in the default mlog config but that was missed.  This PR is to add that to the default config such that all stdlib logs are included.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42345

#### Release Note
```release-note
Logs from third-party libraries are now included in default logging configuration.
```

2022-03-07 18:31 UTC, mkraft approved these changes

2022-03-07 18:32 UTC, mkraft requested changes
We should probably unit test this.

2022-03-08 14:30 UTC, isacikgoz approved these changes
LGTM, 0/5 adding tests.

2022-03-08 19:03 UTC, mkraft approved these changes

2022-03-08 19:22 UTC, merged

2022-03-23 13:39 UTC, wiggin77 commented
> @wiggin77 - Can I get your help identifying the changes required for the product documentation for this feature, please?

@cwarnermm I doubt this requires any documentation changes.  A bit more log output will now happen *if* they are at the debug log level, which is not standard for production.