include deleted posts
mattermost/mattermost-server pull request #20062
Opened 2022-04-25 14:24 UTC by vivek-ng

#### Summary

#### Ticket Link

#### Release Note

```release-note

```

2022-05-07 01:14 UTC, vivek-ng commented
Code reviews here take too much time. I'm no longer interested in contributing to mattermost project . Could you please add the `Up For Grabs` tag again for this issue? Thanks for understanding!

2022-05-09 14:34 UTC, ashishbhate commented
@vivek-ng I'm sorry about the delay in reviewing your PR. I fully understand that this isn't a good experience for our contributors. 

Our developers are occupied with getting things in for the soon to be released v7.0 of Mattermost, which is huge release for us, and which is what caused the delay in getting to your PR. 

Would you consider re-opening the PR? I'm happy to review it right away.

2022-05-10 12:51 UTC, vivek-ng commented
@ashishbhate Thanks for the explanation. I really appreciate it 😄 . I've re-opened the PR. Thank you!

2022-05-10 13:39 UTC, ashishbhate commented
/update-branch

2022-05-11 12:34 UTC, ashishbhate commented
Thanks, @vivek-ng! I'm trying to figure out why the enterprise tests are failing. I'll report back once I've figured out what's going on.

2022-05-12 12:07 UTC, ashishbhate requested changes
Great job @vivek-ng ! 

Some small blocking comments inline. 

The EE tests are failing because the changes in this PR need to be incorporated into that code. I'll make these changes, until then, we can ignore the failing EE tests.

2022-05-12 12:07 UTC, ashishbhate commented on api4/post_test.go
> +	require.Equal(t, th.BasicPost.Id, post.Id)
Could we add a test here for a normal user getting a deleted post with includeDeleted set to false? According to the Jira ticket, this should return a 404

2022-05-19 06:29 UTC, Willyfrog commented on app/plugin_api.go
>  }
as long as it happens under the same circunstances (checking that the user is an admin), it should be ok. If there is no way to check that, then I'd rather not have the plugins circunvent the system.

2022-06-03 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-13 10:07 UTC, Willyfrog commented
Hi @vivek-ng I see there is some feedback from @ashishbhate but no further action, is there something that you might need clarification? Sorry if this is taking too long, as he mentioned before we are releasing a big change in a couple of days and there is a lot of movement, so things fall through the cracks sometimes, but I would love to see this as part of the changes for the next release. Let us know how can we help you.

2022-06-13 14:59 UTC, vivek-ng commented
@Willyfrog This work has already been completed by another PR https://github.com/mattermost/mattermost-server/pull/20358 . I can close this PR 👍

2022-06-13 14:59 UTC, closed without merging