Replace user mentions on account deletion
mattermost/mattermost-server pull request #20136
Opened 2022-05-04 14:51 UTC by tyrandus

#### Summary

This pull request provides a sample implementation of the proposed fix in [this issue](https://github.com/mattermost/mattermost-server/issues/20135). In short, when user accounts are deleted, all messages mentioning them via `@user` have the mention replaced by `@deletedUser`.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/20135

#### Release Note
```release-note
Added user mention anonymization for deleted user accounts.
```

2022-05-05 11:40 UTC, tyrandus commented
/check-cla

2022-05-12 17:05 UTC, agnivade commented
Thanks @tyrandus ! I like the idea but it needs some PM input. I'll ping on the issue.

2022-06-03 17:39 UTC, mkraft commented
<img width="594" alt="Screen Shot 2022-06-03 at 1 34 59 PM" src="https://user-images.githubusercontent.com/1149597/171917292-90fcb5f5-e689-4a88-9346-a8e44c2011a9.png">
<img width="630" alt="Screen Shot 2022-06-03 at 1 34 43 PM" src="https://user-images.githubusercontent.com/1149597/171917296-a229382e-6822-40b8-84b0-e66c15110d8f.png">

I was curious what Slack does so I made a data deletion request and this is how it's displayed in the UI.

2022-06-03 17:39 UTC, mkraft requested changes

2022-06-13 08:44 UTC, tyrandus commented on store/sqlstore/post_store.go
> +	err = transaction.Select(&username, "SELECT Username FROM Users WHERE Id = ? LIMIT 1", userId)
Good point.

2022-06-13 08:46 UTC, tyrandus commented on app/user.go
> +	if err := a.Srv().Store.Post().ReplaceUserMentions(user.Id); err != nil {
True, but I am afraid that moving this to a background job is beyond my Go capabilities.

2022-06-17 14:55 UTC, mkraft commented on app/user.go
> +	if err := a.Srv().Store.Post().ReplaceUserMentions(user.Id); err != nil {
No worries. Thanks for the contribution, I'll link it for reference in a ticket to accomplish this.

2022-06-17 14:58 UTC, closed without merging

2022-06-17 14:58 UTC, mkraft commented on app/user.go
> +	if err := a.Srv().Store.Post().ReplaceUserMentions(user.Id); err != nil {
https://mattermost.atlassian.net/browse/MM-45185