Introduced search for channel id's
mattermost/mattermost-server pull request #20259
Opened 2022-05-22 04:14 UTC by santoniriccardo

#### Summary

#### Ticket Link

#### Release Note

```release-note

```

2022-05-22 04:14 UTC, mattermod commented
Hello @santoniriccardo,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-05-24 15:31 UTC, neallred approved these changes
LGTM! Thanks, @santoniriccardo . I validated by manually doing the request in dev tools with this parameter the mattermost-server instance (https://mattermost-server-pr-20259.test.mattermost.cloud/) since I don't *think* the build system will pick up both forks at the same time.

2022-05-25 08:57 UTC, ashishbhate commented on store/storetest/channel_store.go
> +		{"Search ChannelA by id", o1.Id, store.ChannelSearchOpts{IncludeDeleted: false, IncludeSearchById: true}, model.ChannelList{&o1}, 0},
Can we set Page to 0 and PerPage to something in the ChannelSearchOpts, to confirm that TotalCount is 1 in the test?

2022-05-25 08:58 UTC, ashishbhate commented on store/sqlstore/channel_store.go
> +	}
This can be moved inside the conditional on line 3296.

2022-05-25 08:59 UTC, ashishbhate requested changes
Thanks @santoniriccardo! Looking good. Two small suggestions inline.

2022-05-25 13:14 UTC, santoniriccardo commented
@ashishbhate Resolved!

2022-05-25 15:58 UTC, ashishbhate approved these changes
💯

2022-06-03 05:01 UTC, jgilliam17 commented
/update-branch

2022-06-14 19:51 UTC, jgilliam17 reviewed
Edited: I missed the webapp PR that was linked. Will test there now

Thanks @santoniriccardo 
While testing on the PR test server, I wasn't able to search system console>user management>channels using channel id.
![Screenshot 2022-06-14 154222](https://user-images.githubusercontent.com/52937121/173675892-289a0401-0749-486c-807a-1e2050152acc.png)
Can you please take a look? Thanks 🙂

2022-06-16 13:18 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/208299

2022-06-16 15:31 UTC, jgilliam17 approved these changes
Thanks @santoniriccardo 
I ran the [E2Es](https://mattermost-cypress-report.s3.amazonaws.com/208299-e1a88f5-onprem-ent-server-pr-20259-mattermost/mm-ee-teste1a88f5/mochawesome.html) and will test the changes on the related webapp PR after merge.

2022-06-16 15:32 UTC, merged