MM-44568: sanitizes profiles in posts
mattermost/mattermost-server pull request #20291
Opened 2022-05-25 11:50 UTC by koox00

#### Summary

Sanitizes participant profiles when fetch posts with threads

#### Ticket Link

#### Release Note
```release-note
NONE
```

2022-05-25 12:59 UTC, Willyfrog approved these changes

2022-05-25 13:07 UTC, mkraft requested changes
Could we please add a simple sanity test?

2022-05-25 16:39 UTC, mkraft approved these changes

2022-05-26 04:46 UTC, agnivade approved these changes

2022-05-26 09:58 UTC, koox00 commented
/e2e-test

2022-05-26 09:58 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/198919

2022-05-26 12:25 UTC, ashishbhate approved these changes

2022-05-26 12:41 UTC, merged

2022-05-26 12:41 UTC, mattermod commented
Cherry pick is scheduled.

2022-05-26 12:41 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/mattermost-server
   b8127c039..56629444c  MM-33123_setpostunread-test -> upstream/MM-33123_setpostunread-test
 * [new branch]          MM-41660-utility -> upstream/MM-41660-utility
 * [new branch]          MM-43878-fix-bulk-import -> upstream/MM-43878-fix-bulk-import
   43fb0aeb5..c70373f09  MM-43956_top-channels-graph -> upstream/MM-43956_top-channels-graph
   30bddcab1..1b53fd976  MM-44084_feature_top_threads -> upstream/MM-44084_feature_top_threads
 * [new branch]          MM-44130_change-email-button -> upstream/MM-44130_change-email-button
   2252f4dfa..ba693f8d5  MM-44263_posts-count-perf -> upstream/MM-44263_posts-count-perf
   a06192b32..197f701fa  MM-44475         -> upstream/MM-44475
 * [new branch]          MM-44575         -> upstream/MM-44575
 * [new branch]          add-users-to-map -> upstream/add-users-to-map
 * [new branch]          audit-logging-new-schema -> upstream/audit-logging-new-schema
   2e74391e2..d6a152a08  cloud            -> upstream/cloud
   54a88fb53..3391adb67  master           -> upstream/master
   d88600bdf..3891aaa0d  sidebarcat_index -> upstream/sidebarcat_index
 * [new branch]          top-threads      -> upstream/top-threads
Fetching origin
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
!!! 'upstream/release-7' not found. The second argument should be something like upstream/release-0.21.
    (In particular, it needs to be a valid, existing remote branch that I can 'git checkout'.)

+++ Returning you to the master branch and cleaning up.

```

2022-05-26 17:04 UTC, amyblais commented
/cherry-pick release-7.0

2022-05-26 17:04 UTC, mattermod commented
Cherry pick is scheduled.