new ui for email verification due to change in the email address
mattermost/mattermost-server pull request #21045
Opened 2022-09-19 18:23 UTC by salmanmanekia

#### Summary
This PR updates the email UI which is being sent when the user updates his email address and needs to verify his email.
  

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44790

#### Release Note

```release-note
NONE
```

2022-09-19 18:25 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-09-28 22:07 UTC, julmondragon requested changes
Looks good! Just one item requiring attention.

2022-09-28 22:07 UTC, julmondragon commented on templates/email_change_verify_body.html
> +                                                    <p style="font-family: 'Open Sans';font-style: normal;font-weight: 400;font-size: 14px;line-height: 20px;margin-top: 2px; color: #3F4350;">{{.Props
It looks like these two `p` elements are not taking the expected font family:

<img width="610" alt="Screen Shot 2022-09-28 at 4 50 39 PM" src="https://user-images.githubusercontent.com/79058848/192896497-b08732e0-38a4-431c-b6e8-b23332d7582e.png">

Maybe just need to be set as in other elements of the template: `font-family: Open Sans, sans-serif;`

2022-09-29 10:15 UTC, AGMETEOR approved these changes
LGTM pending Julian's comments

2022-09-29 14:59 UTC, stevemudie approved these changes
Looks good @salmanmanekia!

2022-10-03 15:42 UTC, julmondragon approved these changes
Thanks @salmanmanekia !

2022-10-03 16:29 UTC, annelieseklein commented
Looks great! @salmanmanekia each individual font type needs to be updated to match the design. 
1. heading = Metropolis, semi-bold, 28px
2. Body = open sans, 16 px (16px away from the heading as well)

<img width="523" alt="Screen Shot 2022-10-03 at 9 27 33 AM" src="https://user-images.githubusercontent.com/29821919/193629939-affe6885-bdcb-4b8a-94fc-c6bbd2f412dd.png">

2022-10-04 07:52 UTC, salmanmanekia commented
> Looks great! @salmanmanekia each individual font type needs to be updated to match the design.
> 
> 1. heading = Metropolis, semi-bold, 28px
> 2. Body = open sans, 16 px (16px away from the heading as well)
> 
> <img alt="Screen Shot 2022-10-03 at 9 27 33 AM" width="523" src="https://user-images.githubusercontent.com/29821919/193629939-affe6885-bdcb-4b8a-94fc-c6bbd2f412dd.png">

Hello @annelieseklein, The screen that you have attached is for email verification when a new user is created while the changes in this PR is related to email verification when an email change is requested.

2022-10-06 16:29 UTC, annelieseklein commented
@salmanmanekia for sure, sorry I was referring to the font types which should be the same

2022-10-12 13:44 UTC, neallred approved these changes
LGTM, thanks @salmanmanekia !

2022-10-12 21:10 UTC, annelieseklein approved these changes

2022-10-12 21:10 UTC, annelieseklein commented
@salmanmanekia can you share the updated image of the email please?

2022-10-13 15:41 UTC, annelieseklein commented
@salmanmanekia Great, thanks! "Questions?" should be in semibold

2022-10-14 13:03 UTC, merged