Update Header with application/json
mattermost/mattermost-server pull request #21047
Opened 2022-09-19 19:24 UTC by safakkizkin

#### Summary
Assigned content type application/json for NotFound (404), to stay true to the document.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/20878
JIRA: https://mattermost.atlassian.net/browse/MM-46605

#### Release Note
```release-note
NONE
```

2022-09-19 19:24 UTC, mattermod commented
Hello @safakkizkin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-09-20 11:25 UTC, agnivade commented
@noxer - mind taking a look ? :)

2022-09-21 09:47 UTC, noxer requested changes

2022-09-21 09:47 UTC, noxer commented on web/web.go
> +	w.Header().Set("Content-Type", "application/json")
This should be moved into the `if IsAPICall(a, r) {` block. The other paths don't return JSON.

2022-09-21 09:48 UTC, noxer commented
Hi @safakkizkin and thank you for your contribution. I'd like to request a small change and then this should be good to go.

2022-09-21 16:52 UTC, safakkizkin commented
Hi @noxer, yes you are totaly right!

2022-09-23 15:54 UTC, noxer approved these changes
Looks good, thank you @safakkizkin!

2022-09-24 09:16 UTC, mattermod commented
Successfully triggered e2e testing!
https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/243862

2022-09-27 23:37 UTC, noxer commented
ping @isacikgoz

2022-09-27 23:54 UTC, noxer commented
ping @isacikgoz

2022-09-28 19:20 UTC, safakkizkin commented
rebased to be sure everything is great

2022-09-29 10:39 UTC, noxer approved these changes

2022-09-29 10:46 UTC, isacikgoz approved these changes

2022-09-29 18:18 UTC, merged

2022-09-29 18:19 UTC, noxer commented
Merged, thank you!