Mattercon22 Contribute: Add bio column to users
mattermost/mattermost-server pull request #21108
Opened 2022-09-21 20:13 UTC by ashishbhate

#### Summary

- Added a "Bio" column to the users table, and updated the related app methods. 

#### Ticket Link

- N/A
#### Release Note

```release-note
Added a "Bio" column to the Users tables, with a full text index.
```

2022-10-03 15:27 UTC, sbishel approved these changes

2022-10-18 20:08 UTC, mkraft requested changes

2022-10-18 20:08 UTC, mkraft commented on db/migrations/postgres/000094_add_bio_to_users.up.sql
> +CREATE INDEX IF NOT EXISTS idx_users_bio_txt ON users USING gin(to_tsvector('english', bio));
```suggestion
CREATE INDEX IF NOT EXISTS idx_users_bio_txt ON users USING gin(to_tsvector(bio));
```

According to the [PostgreSQL full text docs](https://www.postgresql.org/docs/15/textsearch-tables.html) we can omit the `'english'` parameter and...

> [the] query will use the configuration set by [default_text_search_config](https://www.postgresql.org/docs/15/runtime-config-client.html#GUC-DEFAULT-TEXT-SEARCH-CONFIG).

2023-01-16 20:08 UTC, mkraft approved these changes

2023-02-09 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-21 15:22 UTC, closed without merging