MM-47228 - restrict guest invitation flow if subscription plan does n…
mattermost/mattermost-server pull request #21195
Opened 2022-10-03 21:21 UTC by pvev

#### Summary
Restrict guest invitation flow if the subscription plan does not support it or is not the free trial

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47228

#### Release Note
```release-note
NONE
```

2022-10-05 11:11 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-10-05 20:22 UTC, marianunez requested changes

2022-10-05 20:22 UTC, marianunez commented on api4/team.go
> +	}
@pvev we should do a general check on license given that the guest restriction should be for both cloud and self-managed - if you are not licensed then you shouldn't be able to allow to invite guests

2022-10-05 20:26 UTC, marianunez commented on api4/team.go
> +	}
It seems we are doing the check in another endpoint to invite guest directly here: https://github.com/mattermost/mattermost-server/blob/master/api4/team.go#L1464

2022-10-05 21:20 UTC, neallred requested changes

2022-10-05 21:20 UTC, neallred commented on api4/team.go
> +	isCloud := c.App.Srv().License() != nil && *c.App.Srv().License().Features.Cloud
I think we should instead check for the feature, e.g. `if c.App.Channels().License() != nil && *c.App.Channels().License().Features.GuestAccounts` . That way, both cloud and self hosted are covered. I think it was just a miss that we never added that check. Then I think we can omit all the subscription and product checking.

2022-10-06 12:47 UTC, neallred approved these changes
Nice add on the unit test helper. LGTM now. Thanks, @pvev!

2022-10-06 12:47 UTC, neallred commented on api4/team.go
> +		c.Err = model.NewAppError("Api4.InviteGuestsToChannels", "api.team.invite_guests_to_channels.disabled.error", nil, "", http.StatusNotImplemented)
:+1:

2022-10-06 12:47 UTC, neallred commented on model/license.go
> +func NewTestLicenseWithFalseDefaults(features ...string) *License {
:+1:

2022-10-06 15:03 UTC, marianunez approved these changes
Thanks @pvev!

2022-10-06 17:18 UTC, srkgupta requested changes
Thanks @pvev. Requested some additional changes. Please see the channel for more information.

2022-10-07 09:04 UTC, srkgupta approved these changes
Thanks @pvev. The changes LGTM.

2022-10-07 13:57 UTC, merged

2022-10-07 14:00 UTC, amyblais commented
/cherry-pick cloud

2022-10-07 14:00 UTC, mattermod commented
Cherry pick is scheduled.