update html lang attribute
mattermost/mattermost-server pull request #22262
Opened 2023-02-06 17:38 UTC by collinewait

### Summary
This PR follows up on this task. https://github.com/mattermost/mattermost-webapp/pull/12159
The HTML tag always has lang="en" even if the language in settings is set to a different language

#### Demo video
Client demo video.
https://www.loom.com/share/19060c7452614ae984e31bc3fb757223

#### Release note
```release-note
Updates HTML lang attribute when a user updates locale
```

2023-02-06 17:43 UTC, collinewait commented
/check-cla

2023-02-13 12:19 UTC, collinewait commented
@hmhealey you can have a look at this. cc @saturninoabril, @mickmister

2023-02-13 15:15 UTC, mickmister reviewed
Thanks for this improvement @collinewait! I have one suggestion that may improve performance

2023-02-13 15:15 UTC, mickmister commented on web/static.go
> +
I wonder if we can do both modifications (this and the `title`) in one passthrough, so we don't end up doing the replace twice

2023-02-13 21:10 UTC, hmhealey commented
I need to see if this is actually possible because of how we cache the `root.html`. I don't know if we'll introduce issues where one user's cached version of this file gets delivered to another user by mistake.

Since this is accompanied by client-side code to update the lang attribute from the client-side, maybe we don't need all this? Alternatively, we could have this code set the `lang` to match the server's locale setting and then have that get overwritten by the user's locale from the web app side

2023-02-14 04:31 UTC, agnivade requested changes
We need to use proper html templates to do the replacements. The same also applies for the openGraphMeta tags.

Some more comments here: https://community.mattermost.com/core/pl/15audd4jypdzi8bwo8pomut3ra

2023-02-15 16:46 UTC, hmhealey commented
@collinewait With the uncertainty around caching and possibly changing the way that the HTML template is rewritten, I think we might not want to make these changes on the server and focus on just the client-side change.

I've tested with a screen reader (JAWS), and the web app changes alone are enough to cause the screen reader to read everything with the correct pronunciation. Also, both Discord and Slack set the `lang` attribute using JS, so I think we can follow their lead here as well by not having a `lang` attribute set in the raw HTML.

2023-02-15 17:01 UTC, collinewait commented
> mattermost/mattermost-webapp#12159

Alright, @hmhealey. Let me address the last comment on the frontend task.

2023-02-15 17:01 UTC, closed without merging