MM-28338 Fix Combined system messages
mattermost/mattermost-server pull request #22608
Opened 2023-03-23 12:47 UTC by Safouene1

#### Summary

[OLD PR (before monorepo) LINK ](https://github.com/mattermost/mattermost-webapp/pull/12088)
Fix the chronological order of combined system messages and remove the priority based sorting as discussed in [here](https://github.com/mattermost/mattermost-server/issues/21926)

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/21926

JIRA: https://mattermost.atlassian.net/browse/MM-28338

#### Related Pull Requests
none

#### Screenshots
Steps to reproduce:
*Create a new public channel.
*Add a user to the channel.
*Post a random message to the channel
*Use the "Manage Member" menu to remove the user
*Use the "Manage Member" menu to add the user back into the channel

|  before  |  after  |
|----|----|
|![image](https://user-images.githubusercontent.com/22036449/215224861-2129363d-a6a3-4b6e-9ab6-fe094bd2032b.png)|![image_2023-01-28_003512141](https://user-images.githubusercontent.com/22036449/215225363-cd9fd3be-895b-48e6-b13a-f2e7fad6d28f.png)|

#### Release Note
```
Fixed a bug where combined system messages are not in chronological order
```
```release-note
Fixed a bug where combined system messages are not in chronological order
```

2023-03-23 12:47 UTC, mattermost-build commented
Hello @Safouene1,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-03-24 21:32 UTC, Safouene1 commented
Hey @hmhealey , Sorry for pinging you but you're the only one informed about everything about this PR.

While working on tests i discovered the following : 
Currently, in the master branch, getting usernames in the combineActivity feature is broken and does not work. However, in this PR, it now works as intended and the issue has been fixed 
on line 333 in post lists

`    messageData.push({postType, userIds: [...usernames, ...userIds], actorId: actorId[0]});
`

However, I noticed that in messageData, we are sending both usernames and userIds to the userIds array. I believe this is unnecessary as the old implementation had broken usernames (empty array), so only IDs were being sent. Additionally, I looked into the combined_system_message and found that it can work without usernames just fine.

I suggest removing usernames from the userIds array (userIds: [...userIds]) to simplify the code and improve its efficiency. Please let me know your thoughts on this.

2023-03-29 20:08 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-03-29 20:11 UTC, hmhealey commented
> I suggest removing usernames from the userIds array (userIds: [...userIds]) to simplify the code and improve its efficiency. Please let me know your thoughts on this.

Yeah, that sounds good to me. I think we used to pass both usernames and user IDs since older system messages were inconsistent of which ones were included in the post props, but since you have to go really far back to see those posts now, I think it's fine to not pass both of them. I definitely appreciate all the work you're doing to help clean this code up 🙂

2023-04-04 05:07 UTC, Safouene1 commented
I've updated tests and added a filter to null values in AllUserIDS and AllUsernames.

2023-04-05 20:24 UTC, hmhealey commented
Cool, let me know when this is ready for review again then

2023-04-08 01:20 UTC, Safouene1 commented
Hey ! I deleted the 2 tests because the combine system messages do not handle those operations anymore. 
Should be good now.

2023-04-11 20:03 UTC, hmhealey commented
Cool, I'll review that shortly. I had to merge master again to get the CI tests unblocked, so hopefully that's okay with you. One day, we'll stop changing those constantly

2023-04-11 20:13 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/324285) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/324285)

2023-04-11 20:18 UTC, hmhealey requested changes
Thanks for updating all those tests. I have one small suggestion to make an if statement a bit easier to read, but otherwise, this looks good to me

2023-04-11 20:18 UTC, hmhealey commented on webapp/channels/src/packages/mattermost-redux/src/utils/post_list.ts
> +        if ((isSamePostType && isSameActor && prevPost) || (isSamePostType && prevPost && isRemovedPost)) {
```suggestion
        if (prevPost && isSamePostType && (isSameActor || isRemovedPost)) {
```

2023-04-11 20:25 UTC, hmhealey commented
Looks like the tests are also failing because an old snapshot needs to be removed

2023-04-11 20:57 UTC, Safouene1 commented
> Looks like the tests are also failing because an old snapshot needs to be removed

Sorry about those , I forgot about deleting them when I deleted the 2 tests. Will update asap

2023-04-14 16:10 UTC, hmhealey approved these changes

2023-04-24 18:02 UTC, koox00 approved these changes
Thanks @Safouene1 💯

2023-04-25 09:31 UTC, koox00 commented
/e2e-tests

2023-04-25 09:31 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/329263) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/329263)

2023-04-25 09:36 UTC, koox00 commented
/update-branch

2023-04-25 14:29 UTC, hmhealey commented
@Safouene1 We're also going to want to make these changes on our mobile app as well. If we open that as another help wanted ticket, would you be interested in working on that as well? If not, that's totally fine too

2023-04-25 14:31 UTC, Safouene1 commented
> @Safouene1 We're also going to want to make these changes on our mobile app as well. If we open that as another help wanted ticket, would you be interested in working on that as well? If not, that's totally fine too

I would love to give it a try

2023-04-26 07:27 UTC, Safouene1 commented
Great ! Please assign me or mention me in the new ticket.
I will setup the environment and development in the weekend

2023-04-28 21:26 UTC, furqanmlk approved these changes
Working as expected

**Before**

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/6909890/235256538-2431cb38-f95d-42ee-ab63-8a5a8c0ac079.png">

**After**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/6909890/235256658-f4c45093-7949-471a-8700-d09edfca58dc.png">

2023-05-04 15:09 UTC, merged