MM-40566 Remove collapse from websocket sync
mattermost/mattermost-server pull request #22607
Opened 2023-03-23 12:16 UTC by Safouene1

#### Summary
[OLD PR before Monorepo ](https://github.com/mattermost/mattermost-webapp/pull/12186)
Stop Websocket from changing category.collapse state.
Keep Websocket syncing , just not change the state only for Collapse/Expand state.
**More details  in the Issue linked below.** 

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/22044

 JIRA ticket : https://mattermost.atlassian.net/browse/MM-40566

#### Release Note

```release-note
remove websocket state effects for the collapse/expand state of categories
```

2023-03-23 18:39 UTC, hmhealey commented
Thanks for moving this over! This looks good to me, but it looks like the linter has some complaints. Mind fixing those?

2023-03-24 20:10 UTC, Safouene1 commented
> Thanks for moving this over! This looks good to me, but it looks like the linter has some complaints. Mind fixing those?
Sorry about those , I forgot to turn on the linter for the monorepo , I pushed the changes

2023-03-29 21:03 UTC, hmhealey approved these changes

2023-03-29 21:03 UTC, hmhealey commented
Looks good to me. The remaining CI failures are just due to the code that prepares test servers not being able to run on community PRs right now

2023-04-15 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-04-27 22:42 UTC, stevemudie commented
/e2e-test

2023-04-27 22:42 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/330472) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/330472)

2023-04-28 09:19 UTC, Safouene1 commented
Hey , Are the failing E2E tests in relation to my code? Is there anything I can help with?

2023-04-28 19:56 UTC, stevemudie approved these changes
The failed E2E tests don't appear to be related to your work @Safouene1 
This is all set. Thank you!

2023-05-02 21:11 UTC, hmhealey commented
I'm going to give this another update to see if that fixes CI. I have no idea why any of that would be failing based on the changes you've made

/update-branch

2023-05-02 21:22 UTC, hmhealey requested changes
@Safouene1 I didn't realize the type check is actually failing because of these changes. Would you mind fixing that?

It looks like some Playbooks code is using `fetchMyCategories`, so we could make `isWebSocket` default to false to fix it

2023-05-02 21:24 UTC, Safouene1 commented
> It looks like some Playbooks code is using `fetchMyCategories`, so we could make `isWebSocket` default to false to fix it

Thank god CI exist  , Yes I will update it this week.

2023-05-04 08:52 UTC, Safouene1 commented
Should work fine now , could someone run the e2e testa

2023-05-04 20:38 UTC, stevemudie commented
/e2e-test

2023-05-04 20:39 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/333104) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/333104)

2023-05-05 15:50 UTC, hmhealey requested changes

2023-05-05 15:50 UTC, hmhealey commented on webapp/playbooks/src/components/backstage/playbook_editor/playbook_editor.tsx
> +        dispatch(fetchMyCategories(teamId,false));
```suggestion
        dispatch(fetchMyCategories(teamId, false));
```

2023-05-05 20:35 UTC, hmhealey commented
Thanks for the quick update. I'll kick those tests off again. It's annoying right now that the CI needs one of us to approve it before it tells you simple stuff like that :/

2023-05-05 20:39 UTC, Safouene1 commented
> It's annoying right now that the CI needs one of us to approve it before it tells you simple stuff like that :/

 I agree that it would be helpful to have at least the linting and i18n tests launch automatically without requiring manual approval. That would save a lot of time and effort in the long run.

2023-05-10 14:00 UTC, merged

2023-05-10 14:03 UTC, hmhealey commented
Thanks again for that change! I definitely appreciate this one since I'm the one that introduced the bug, but I never got around to fixing it myself