Rename workflows to make it clearer
mattermost/mattermost-server pull request #23316
Opened 2023-05-05 15:07 UTC by agnivade

Mattermost build was a confusingly named workflow. Changed it
to Server CI to make it consistent with Webapp CI.

Also changed the filenames.

```release-note
NONE
```

2023-05-05 15:09 UTC, isacikgoz approved these changes

2023-05-05 16:22 UTC, toninis approved these changes

2023-05-05 16:24 UTC, toninis requested changes
You need to change also the artifacts workflow file condition. It depends on this name

2023-05-08 06:18 UTC, agnivade commented
PTAL @toninis

2023-05-08 06:24 UTC, toninis approved these changes
🚀

2023-05-08 07:42 UTC, m1lt0n approved these changes

2023-05-08 07:43 UTC, merged