Migrate "components/admin_console/set_by_env.jsx" to Typescript
mattermost/mattermost-server pull request #23451
Opened 2023-05-18 17:18 UTC by tejaskarelia17

#### Summary
In this PR, completes migration of `components/admin_console/set_by_env.jsx` to TypeScript.

#### Ticket Link
Fixes [GitHub issue #23419](https://github.com/mattermost/mattermost-server/issues/23419)

#### Release Note

```release-note
NONE
```

2023-05-18 17:18 UTC, mattermost-build commented
Hello @tejaskarelia17,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-05-19 10:34 UTC, M-ZubairAhmed submitted a review, later dismissed

2023-05-19 10:34 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/set_by_env.tsx
> +const SetByEnv: React.FunctionComponent = (): JSX.Element => {
we actually don't have to convert this to an anonymous function. its fine as it was before with default export. This conversion might actually be changing the file extension :D

2023-05-19 10:35 UTC, M-ZubairAhmed requested changes
Please check the above comment

2023-05-20 14:56 UTC, M-ZubairAhmed approved these changes

2023-05-20 22:27 UTC, sinansonmez approved these changes
LGTM 👍

2023-05-22 10:45 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-05-29 08:46 UTC, yasserfaraazkhan approved these changes
thank you for the changes 
e2e have passed 

https://github.com/mattermost/mattermost-server/pull/23515

2023-05-29 09:00 UTC, merged